### ISSUE TITLE
Synchronize Server

### ISSUE THREAD

**Issue by Sakrust** [carla-simulator/carla#1027]
I know this feature is currently not implemented, but can you give me a hint how to easily implement a do_tick() function, stepping through the simulator frames?

**Comment by nsubiron** [comment]
Not so difficult but not so trivial either. Basically, you would need to port the synchronous mode we had in 0.8.x API and make it work with the new system. I think the main complication comes from the fact that you have now any number of clients, so I client has to somehow tell the simulator to wait for it every tick, and we have to decide if we want to have just one or multiple "synchronous clients".

This is however among the top tasks of our priority list, we expect to have this implemented soon, during January or February.

**Comment by sapirbm** [comment]
hey @nsubiron,
i started looking into the server code and comparing 0.9.1 to 0.8.4. i saw that there is some code regarding the "SyncronousMode" that still being implemented. can you please refer me to the set of elements (functions, flags, structs) needed to port in order to make this mode working?
in summary, what exactly needs to be ported?...

**Comment by Sakrust** [comment]
Any progress on this issue?

**Comment by mango009** [comment]
It would be highly desirable to have this feature implemented. I'm currently working on a project that we would need to trigger the simulation frame-by-frame from the client. Would be appreciative if anyone can give an update.
