### ISSUE TITLE
Procedural export of map

### ISSUE THREAD

**Issue by Iftimie** [carla-simulator/carla#1052]
Hello Carla team,

I would like to know what is the best way to have access to every object in the world and every vertex of that object.
I wish to procedurally export the 3D representation (bbox or vertices) of the object in the world, so that I can render them myself.
The reason I want to do this is because I need a top down view of the environment like in this paper (ChauffeurNet) https://arxiv.org/pdf/1812.03079.pdf
Of course, I could use semantic segmentation and translate the camera above the car looking down, but I need precise information about where in the world is something like a traffic light or a marking lane.

I saw in Python API reference that for the class world there is a method get_actors(), but it only returned the traffic lights objects (since I had no other agent). I also thought of writing some C++ code for that, but I don't have that much experience with Unreal. If the C++ code is the best way to go, do you have any suggestion like what kind of class to inherit, or how to execute that code? I compiled last weekend the source code so many times that I began to become familiar with the project structure.

Thank you for your help.

**Comment by backer777** [comment]
Hello @Iftimie 
`I would like to know what is the best way to have access to every object in the world and every vertex of that object.
I wish to procedurally export the 3D representation (bbox or vertices) of the object in the world, so that I can render them myself.`

Now I have a problem. There is a triangular road sign model in the scene, and I want to get its vertices coordinates . Do you have a new solution?  
Thank you.
