### ISSUE TITLE
Constant speed control

### ISSUE THREAD

**Issue by giladdiv** [carla-simulator/carla#1088]
I want to create a scenario where two cars collide at a constant speed (one is not moving and one at x km/h).
Is there a way to set a fixed speed to a vehicle?

And on a different subject, Is there a way to get the true bounding box of one car as observed by another car's camera?

Thanks

**Comment by marcgpuig** [comment]
Hi @giladdiv 
It depends on the version of Carla you are using.
If you are with 0.9.x you can set a fixed throttle to a car and set another car on a certain position easily with your python client. Otherwise, using 0.8.x, you must do it manually inside the Unreal Editor.

> And on a different subject, Is there a way to get the true bounding box of one car as observed by another car's camera?

What do you mean with _the true bounding box_?
