### ISSUE TITLE
Python API for Carla 0.9.3 requires libpng16  incompatible with ROS

### ISSUE THREAD

**Issue by anshulpaigwar** [carla-simulator/carla#1270]
Python API for Carla 0.9.3 requires libpng16 while ROS and Gazebo still work with libpng12. When I installed libpng16 using `apt-get` it auto removes some important Gazebo and ROS files. I think Carla should also stick to libpng12 for a while. Is there any way to install both libpng16 and libpng12 ??

**Comment by nsubiron** [comment]
This is a known issue, unfortunately we don't know how to fix this except by removing PNG support #924. The problem is that we use Boost GIL for handling images, and as it turns out is not compatible with libpng12.

**Comment by jkewang** [comment]
I think you can reinstall ros-kinetic-gazebo* after installing Carla. I did this way and they both work well in my machine.

**Comment by anshulpaigwar** [comment]
Thank you @jkewang this worked for me too.

**Comment by wattsavolt** [comment]
Did you ever try FreeImage? Link to python wrapper: http://freeimagepy.sourceforge.net/

**Comment by rohanb2018** [comment]
I actually found another solution that doesn't require reinstalling ROS. If you install the `libpng16-16` package (which only has the libpng runtime library files) instead of `libpng16-dev`, none of the Gazebo/ROS files will be removed. And it seems that the CARLA Python API works fine with only the runtime library files: I tried the `tutorial.py` script and it saved the PNG files without a hitch.

Hopefully this works for others as well.
