### ISSUE TITLE
carla.Map.get_waypoint(...) and debug draw functions cause navigation issues for BasicAgent

### ISSUE THREAD

**Issue by argh1** [carla-simulator/carla#1278]
Using CARLA 0.9.3 on Ubuntu 16.04:

When using the BasicAgent (from carla/PythonAPI/agents/navigation/basic_agent.py), if I make calls to carla.Map.get_waypoint(...) in-between steps, it causes the agent to swerve. The more calls I make to get_waypoint in-between steps, the more wildly it swerves. It doesn't seem to matter which location I put for get_waypoint or whether the project_to_road function is set to True or False. Is the get_waypoint function mutating some sort of state which affects the way BasicAgent navigates?

Additionally, I noticed that when I use the debug draw commands to draw out the path that the BasicAgent should be taking, this causes the agent to immediately drive off to the side in one direction and off the road. I tried setting the z coordinate to be much higher than the vehicle, though maybe it's a conflict with objects only in the x and y coordinates? Not sure why a debug draw function would affect the navigation of the BasicAgent.

Any help is appreciated. Thank you!

**Comment by slyer0009** [comment]
I experienced similar issues when spawning multiple Vehicles with an attached BasicAgent. Especially with more than 3 BasicAgents they all go nuts (obviously the steering PID doesn't work, timing issue?). 
Maybe this correlates to your problem.

**Comment by argh1** [comment]
Even if I spawn only one BasicAgent, these calls cause swerving. When I get rid of these calls, the problem mostly goes away, but I have noticed that in certain cases (such as relocating the vehicle back to its original position and trying to run the same course) can cause the navigation to go haywire and veer off to the side, similar to what the debug draw commands would cause. This makes me think that perhaps there is an invisible object in the area that the vehicle could drive through but is interfering with the navigation somehow.

**Comment by Sakrust** [comment]
I think this is mainly caused by synchronisation issues, as the server doesn't wait for input from client side. 
Those debug draw functions directly interact with the simulator view and significantly slow down your client, causing the frames of Unreal not executed synchronously to the client steps. I have had similar problems and always blamed them on the missing sync.

You would expect Unreal to take recently calculated values as input for each step, but if your client is too slow, the simulator uses the values calculated in the last step leading to unstable behaviour. 
I guess this will be fixed in 0.9.4, refer to #1244

**Comment by samruddhida** [comment]
How do I assign a BasicAgent to a vehicle? When I run the code on its own, it doesn't show anything on the simulator
