### ISSUE TITLE
How to save key press info in manual_control.py?

### ISSUE THREAD

**Issue by geekhut** [carla-simulator/carla#1284]
I would like to save a sequence of actions (for walker/pedestrian) that I carry out manually with manual_control.py, and replicate the same sequence of actions on another walker (a separate python script possibly) when I run it. It should make the same sequence of actions.. How should I go by doing it?

**Comment by YashBansod** [comment]
Just store the values read in the `KeyboardControl._parse_vehicle_keys(self, keys, milliseconds)` in some array and save it to the disk.  
A better way would be to actually store the carla.VehicleControl() values and parse that. However, since there is no synchronous mode in 0.9.X versions, don't expect it to work correctly.
