### ISSUE TITLE
tcp error all the time

### ISSUE THREAD

**Issue by zlw21gxy** [carla-simulator/carla#1307]
hey guys, currently I am ray to train my carla client, I use a wrapper to make carla service more like gym environment [https://github.com/zlw21gxy/carla/blob/master/env.py](url)
but during training, this kind of message always show up, does anyone knows why? thanks a lot

Clearing Carla server state
Error during step, terminating episode early Traceback (most recent call last):
  File "/data/carla/PythonClient/carla/tcp.py", line 67, in write
    self._socket.sendall(header + message)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kychen/gu/project/carla/env.py", line 412, in step
    obs = self._step(action)
  File "/home/kychen/gu/project/carla/env.py", line 447, in _step
    reverse=reverse)
  File "/data/carla/PythonClient/carla/client.py", line 145, in send_control
    self._control_client.write(pb_message.SerializeToString())
  File "/data/carla/PythonClient/carla/tcp.py", line 69, in write
    self._reraise_exception_as_tcp_error('failed to write data', exception)
  File "/data/carla/PythonClient/carla/tcp.py", line 97, in _reraise_exception_as_tcp_error
    raise TCPConnectionError('%s%s: %s' % (self._logprefix, message, exception))
carla.tcp.TCPConnectionError: (localhost:51174) failed to write data: [Errno 32] Broken pipe

Start pos 75 ([-7, 158]), end 16 ([131, 105])
Starting new episode...
ERROR: tcpserver 47883 : error reading message: End of file 
Start pos 21 ([27, 187]), end 1 ([-3, 142])
Starting new episode...
ERROR: tcpserver 15688 : error reading message: End of file 
Start pos 74 ([189, 208]), end 32 ([162, 237])
Starting new episode...

ERROR: tcpserver 36066 : error reading message: End of file 
ERROR: tcpserver 0 : error reading message: Operation canceled 
ERROR: tcpserver 30452 : error reading message: End of file 
ERROR: tcpserver 0 : error reading message: Operation canceled 
ERROR: tcpserver 0 : error reading message: Operation canceled 
ERROR: tcpserver 0 : error reading message: Operation canceled 
Start pos 21 ([27, 187]), end 1 ([-3, 142])
Starting new episode...
Start pos 3 ([135, 226]), end 23 ([75, 187])
Starting new episode...
ERROR: tcpserver 36772 : error reading message: End of file 
ERROR: tcpserver 0 : error reading message: Operation canceled 
ERROR: tcpserver 0 : error reading message: Operation canceled 
ERROR: tcpserver 0 : error reading message: Operation canceled

**Comment by AlexVeuthey** [comment]
Hi,

I'm coming from the Self-Driving Cars specialization on Coursera, which I can't finish (last assignment...) due to a TCPError in the server. I'm really not familiar with Carla itself, so it might be something extremely trivial to someone with a bit more knowledge.

I don't know what Carla version we use (haven't checked how I can verify it, though), since it's a precompiled archive given by the course directly. I also don't know if this is an issue with:
- the version shipped by the course,
- the modifications brought by the course's team (if any),
- my installation,

but I'm asking here anyway, since nobody is responding on the course's forum...

The server keeps "restarting", and the display window freezes until it's restarted each time. I've tried without success:
- running on Windows and Ubuntu (Ubuntu is my main platform, and it is more practical as errors appear in the console directly),
- running on different ports,
- reducing the resolution (to check if computation was a slowing issue).

I have the following error message just before it restarts:
```
ERROR: tcpserver [2020.08.19-17.38.26:740][ 2]LogCarlaServer: Warning: Failed to initialize, server needs restart
0 : error reading message: Bad file descriptor
```

Trying to connect the client (hoping it's a normal behaviour while waiting for clients), I get:
```
ERROR: (localhost:9001) failed to read data: [Errno 104] Connection reset by peer
```

Thanks for any help,

Alex
