### ISSUE TITLE
Cannot find the recording file manual_recording.rec

### ISSUE THREAD

**Issue by zhang-xinxin** [carla-simulator/carla#1465]
I want to test the logging and playback feature on Carla 0.9.4 pre-compiled version. I run the manual_control.py, start/stop the recording using CTRL+R, and then playback with CTRL+P. The feature works well. 

But I couldn't find the "manual_recording.rec" file in the carla root directory.  Could you tell me where was it saved? I'd like to analyze its format and create a customized .rec file to playback.  Thanks!

**Comment by zhang-xinxin** [comment]
I finally found the file in /CARLA_ROOT/CarlaUE4/Saved/ directory. It's a binary file. How could I parse the file format and edit it?

**Comment by bernatx** [comment]
Hi zhang-xinxin,

We have written a description of the binary file format (.LOG) used for the recorder system, so you can understand how to parse the file if required. 

It will be ready probably for the next release (0.9.6).

What is not clear is why do need to edit the file, because it may be corrupted after that.

Regards

**Comment by 0102TH** [comment]
carla 0.9.6，I found it here.
![image](https://user-images.githubusercontent.com/47203090/70197839-0eb44200-1748-11ea-9e57-4c54c91f770f.png)

**Comment by icaropires** [comment]
Just to help anyone googling, in Linux with CARLA 0.9.11, it's under `~/.config/Epic/CarlaUE4/Saved/manual_recording.rec`.
