### ISSUE TITLE
Synchronous mode

### ISSUE THREAD

**Issue by moein1924** [carla-simulator/carla#1961]
In the section explaining 'Synchronous mode' it is stated that : 

Note that data coming from GPU-based sensors (cameras) is usually generated with a delay of a couple of frames respect to data coming from CPU-based sensors.

So i am asking, does it mean that in general case, GPU based sensors always have delays or it is only in Synchronous mode ?

**Comment by Soolek** [comment]
It's quite the other way round - based on my experience, if you set quite long time intervals in synchronous mode, the GPU-based sensors will eventually catch up to the CPU-based ones. 

As it was stated by authors, the recent fps gains are mostly due to buffering some of the UE4 graphic output. Take a look at #1212 where the bounding boxes are generated server-side and client-side. The more you wait in synchronous mode the better they align.
