### ISSUE TITLE
Carla server (0.9.6) crashes

### ISSUE THREAD

**Issue by walzimmer** [carla-simulator/carla#2057]
The Carla server (0.9.6) crashes with the error: `Segmentation fault (core dumped)`

![image (23)](https://user-images.githubusercontent.com/22540236/63913284-ed003c00-ca2f-11e9-8b02-cc6b683bffd8.png)

CARLA version number: 0.9.6
Platform/OS: Linux (Ubuntu)

**Comment by cassfalg** [comment]
What's up with everyone uploading screenshots of text terminals recently? What happened to good old copy and paste? Anyway.

To me this looks like you ran out of graphics memory. You can check this with the `nvidia-smi` tool if you got an Nvidia card. What you can also try is the OpenGL engine, instead of the Vulcan one. You need to add the `-opengl` flag.

**Comment by ZainabKhaled** [comment]
This crashing problem is solved?

**Comment by AndreasPapandreou** [comment]
Hello,

I have the same issue, Carla server (0.9.9.3) crashes almost every time I am trying to run it. The most frequent errors are: 
1. Segmentation fault (core dumped)
2. RuntimeError: time-out of 200ms while waiting for the simulator
I am running the default configuration of Carla settings and I am not running out of graphics memory (GPU used: RTX2080 Ti).
I tried also to add the -opengl flag but the issue remains.
