### ISSUE TITLE
Vehicle.set_location problem fix schedule

### ISSUE THREAD

**Issue by Zealoft** [carla-simulator/carla#2075]
About a month ago I reported an issue about the vehicle.set_location problem, and developer told me that it’s an emergency issue which should be fixed soon. [https://github.com/carla-simulator/carla/issues/1875](url)
Actually I’ve been stuck with this problem recently, so is there any news about the fix of this bug? Thank you very much!

**Comment by travelbureau** [comment]
I'll second that this is a big problem. Please move this issue to the front of the queue. 

After spending a large amount of effort to ensure that our test vehicle stack is deterministic we still get non-determinism due to this bug. More importantly its not things like clouds in the sky which is easily cropped, the poses themselves are wrong. 

We have tried pre-computing the height that the vehicles should be placed at (to avoid the 'drop' from the sky) and the results are still somehow not repeatable.
