### ISSUE TITLE
synchronous mode

### ISSUE THREAD

**Issue by kimiya66** [carla-simulator/carla#2103]
when I run the simulator in synchronous mode, it does not show any actor in the view(world) or I have a graphical problem but I could see that the simulation is running (through cmd), however, nothing is shown in the map.
Did anyone confront with the same problem before? or how can I fix it?

Thanks a lot

**Comment by cassfalg** [comment]
Is there a client that "ticks", meaning calls world.tick() regularly? What's your setup exactly? Why do you assume that an actor should be shown in (which?) view?

**Comment by kimiya66** [comment]
> Is there a client that "ticks", meaning calls world.tick() regularly? What's your setup exactly? Why do you assume that an actor should be shown in (which?) view?

Thanks for message,
Why I assume that an actor should be shown? ...by actor I meant vehicles and I could not see results of spawn_actor() in the scene. However, when it is not in synchronous mode it spawns them. and I do not set anything for client tick

**Comment by ndeshp2s** [comment]
@kimiya66, 

Did you manage to resolve this issue? I am having same problem.

**Comment by jrojoCI3** [comment]
Hello,
When you work in asynchronous mode the server updates as fast as it can. This, in exchange, may produce bounces in the fps as some situations may be resolved faster than others. Basically it works as common games.

Synchronous mode, however, is meant specially for simulation where we need consistency in timesteps, so what the server does is wait for the client to announce that it is ready, and then performs all the operations given (for example spawn_actor() ) taking as long as it needs, knowing that the simulation time is fixed (in 10 fps, it would mean 0.1 secs each calculation cycle).

Due to this behaviour it needs the client to call world.tick() in order to announce that "he has finished". I hope this was clear and useful to you.
