### ISSUE TITLE
Linking automative materials using command lines

### ISSUE THREAD

**Issue by Seth-Park** [carla-simulator/carla#226]
Hi,

The document in `http://carla.readthedocs.io/en/latest/how_to_add_automotive_materials/` only gives instructions on linking the automative materials through an editor.

Is there a way to link the materials from the command line prompt? I am trying to install carla on a remote machine that I do not have GUI access to.

Thanks!!

**Comment by nsubiron** [comment]
Hi @Seth-Park,

As far as I know there is no way of doing so. If you are using CARLA without modifications you can download the compiled binary from the [latests release](https://github.com/carla-simulator/carla/releases/latest) page. Otherwise I'm afraid you'll have to compile a binary version yourself in a machine with display and then copy it to the remote machine.

Cheers,
