### ISSUE TITLE
Semantic segmentation - Car windows

### ISSUE THREAD

**Issue by carlaUser** [carla-simulator/carla#2342]
I have noticed that the car windows are completely transparent to the segmentation camera, i.e. the segmentation algorithm will label the corresponding pixels as whatever is behind them, **regardless of how opaque the windows are**.

In the following pictures, we can see that, despite of the windows being completely visible and near opaque in the RGB image, part of the windshield is labeled as road (which, in turn, is barely visible).

![rgb-000299837](https://user-images.githubusercontent.com/59649190/71990099-17aa9e80-3233-11ea-8716-0b789406a26e.png)
![seg-000299837](https://user-images.githubusercontent.com/59649190/71990111-1bd6bc00-3233-11ea-9821-cf26d79ccb1b.png)

Is this the intended behavior? Otherwise is any fix planned?

**Comment by jeffreykxiao** [comment]
I can confirm this issue. In my opinion, it should not be the intended behavior as a car window should for all intents and purposes still be semantically part of a vehicle. 

The fix is simple:
![image](https://user-images.githubusercontent.com/2986354/72031989-758dc380-32d1-11ea-89dc-f5927b48dd2f.png)
Translucent materials have an additional property to allow custom depth writes (this incurs a performance cost as they are normally excluded from the custom depth pass since they need to be handled last). As long as the base material for all car glass, which I believe is Static/Vehicles/GeneralMaterials/Glass.uasset has this flag changed, all material instances using Glass.uasset will be rendered in custom depth.

However, as Carla content is distributed through AWS / Google Drive, there is no way for a user to push this fix. If you have an editor build you can change this for yourself, but otherwise you will need to wait on a new asset pack / new release.

**Comment by meteorshowers** [comment]
could you please share your fixed version?
Thanks!

**Comment by guygo12345** [comment]
Hey!
I'm also interested. If you can would love to get the fix :)

**Comment by magehrig** [comment]
This issue still persists in 0.9.9

**Comment by guygo12345** [comment]
It seems like this issue isn't going to be solved, but meanwhile I'm attaching here the updated uasset file.
If you want to use it just replace the original with this
[glass.zip](https://github.com/carla-simulator/carla/files/4883228/glass.zip)
