### ISSUE TITLE
Wait until fully rendered feature?

### ISSUE THREAD

**Issue by carlaUser** [carla-simulator/carla#2345]
I am working on a script that would spawn vehicles at determined points and record some shots of them. I am currently waiting until all the vehicles are completely stopped for recording, but even then the pictures taken by the cameras show scenes that are not fully rendered. An example of this can be seen in the image below:

![test_img3](https://user-images.githubusercontent.com/59649190/71992723-2b0b3900-3236-11ea-8da1-1aad95f4db09.png)

Here we can see that the texture of the CarlaCola truck is clearly not fully rendered. Paying closer attention it is also possible to see that the level of detail of all the vehicles, as well as that of the bike rider, is quite low.

On the other hand, if I change the weather right before the shot, the presence of rain or lack thereof will be given by the previous weather, since the camera will be faster than what it takes the rain to start/stop falling.

I have tried using `world.wait_for_tick()`, but it does not fully solve my problem. If I wait around one second before each shot after having set everything up it does the trick (at least so far), but it doesn't look to me like a reliable solution. Is there any other alternative to solve this problem?

**Comment by jeffreykxiao** [comment]
I'm going to take a stab in the dark and suggest disabling texture streaming. I assume that the "Carla Cola" truck logo is a slow-to-load texture. Unfortunately, Carla is provided as a shipping build so you won't be able to run console commands to test this out - if you have a build you compiled yourself, you can type ` r.TextureStreaming 0` into the in-game console to see if it helps. 

If you only have a release, you may be able to mess with some configs prior to launching the program. In the releases's config file, create (or edit if it is already there) a DefaultEngine.ini file. Under the section `[/Script/Engine.RendererSettings]`, you should change or add this line: `r.TextureStreaming=False`. You might also want to try `r.DefaultFeature.MotionBlur=False` because it is not a useful option for static pictures. After changing these configs, try launching the release again (note that if you are using the latest release, do not mess with the -quality-level command-line argument as it is bugged: see #2335 )
