### ISSUE TITLE
make PythonAPI does not work on Windows 10

### ISSUE THREAD

**Issue by xuyanwen2012** [carla-simulator/carla#2463]
Hello there,
My lab members and I have been stuck on this for many days already. 
We are trying to build Carla on Windows 10 machines, and the CarlaUE4 actually runs ok. ```make launch``` works perfectly, and Unreal is working, and we can play it. However, when trying to make the PythonAPI, ```make PythonAPI```, we have encountered many issues.

![image](https://user-images.githubusercontent.com/17172671/74292065-e1f24d00-4ceb-11ea-8b32-4a866d7f499a.png)

It is telling me Carla lib has been successfully installed but it is showing tons of linker errors. And I don't see any ```dist``` files been generated. 

And I therefore could not run the example python scripts.

![image](https://user-images.githubusercontent.com/17172671/74292174-35649b00-4cec-11ea-97e8-d9b19ece5c95.png)

- I am using the ```x64 Native Tools Command Prompt for VS 2017```
- I have ```Desktop Development with C++``` && ```Windows 8.1 SDK``` checked
- I am using ```Python 3.7.6``

Does anyone have encountered similar situations before? Please advise what should I do next.

Thank you very much.

**Comment by ixfd64** [comment]
I'm also getting an error, although it's not the same.

`Traceback (most recent call last):
  File "setup.py", line 131, in <module>
    ext_modules=get_libcarla_extensions(),
  File "setup.py", line 91, in get_libcarla_extensions
    libs = [x for x in os.listdir('dependencies/lib') if any(d in x for d in required_libs)]
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'dependencies/lib'`

Could it be related?

**Comment by robogast** [comment]
I'm not sure if this exactly the issue, but it smells like it. See #1466.

The errors you show above smell specifically like errors with boost, although I'm not entirely sure what a fix for those would be.

**Comment by Julian9875** [comment]
@xuyanwen2012 I have the exact same issue. Have you found the solution yet?

**Comment by xuyanwen2012** [comment]
> @xuyanwen2012 I have the exact same issue. Have you found the solution yet?

Not yet, I am temporary getting around with this by switching to Linux (WSL). Although WSL have other issues that does not let me to launch the UE4editor, but at least the ``make PythonAPI`` can work. So I had my server running on Windows and the client running in WSL (kinda sucks, but at least it works).

**Comment by j4l-Shvn** [comment]
Same here....seems like Windows was never built for driving simulator APIs :) ... possibly PACMan at the most.... Also, if we try the pypi version or the one that ships with the latest windows release i.e. carla 0.9.5 it throws the same "dependencies/lib" error..... made me believe I need to build it from scratch.. suffered miserably.... switched to linux instead...

**Comment by carfloresp** [comment]
Hi @xuyanwen2012 , I faced the same problem and managed to get around it. After compiling Carla client and server, instead of "make PythonAPI", I did:

cd PythonAPI/carla
python setup.py install

This generated the /dist folder and the ".egg" file within. I am able to run the .py examples now.
Hope this helps in your case.

**Comment by gn01121991** [comment]
Hi, I faced a similar issue recently, i solved the issue my opening the command prompt x64 Native Tools Command Prompt for VS 2017 with admin rights and followed steps mention in comment from @carfloresp ( path to carla\PythonAPI\carla and run python setup.py install)

**Comment by kartikeyshaurya** [comment]
Thanks for the help i faced the similar issue now its working 💯

**Comment by jzl20** [comment]
> elated

**Comment by MarissaCampa** [comment]
> Hi @xuyanwen2012 , I faced the same problem and managed to get around it. After compiling Carla client and server, instead of "make PythonAPI", I did:
> 
> cd PythonAPI/carla
> python setup.py install
> 
> This generated the /dist folder and the ".egg" file within. I am able to run the .py examples now.
> Hope this helps in your case.

Thanks for the help @carfloresp , this method worked for me too!

**Comment by arogyaGurkha** [comment]
> I'm also getting an error, although it's not the same.
> 
> `Traceback (most recent call last): File "setup.py", line 131, in <module> ext_modules=get_libcarla_extensions(), File "setup.py", line 91, in get_libcarla_extensions libs = [x for x in os.listdir('dependencies/lib') if any(d in x for d in required_libs)] FileNotFoundError: [WinError 3] The system cannot find the path specified: 'dependencies/lib'`
> 
> Could it be related?

Its been a few years but did you find way to solve this?

**Comment by jzl20** [comment]
&nbsp;
***@***.***



&nbsp;
system can not find the dir&nbsp; &nbsp;'dependencies/lib'
try to use the [full path] instead of [relative path]


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "carla-simulator/carla"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月17日(星期六) 下午2:23
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [carla-simulator/carla] make PythonAPI does not work on Windows 10 (#2463)





  
I'm also getting an error, although it's not the same.
 
Traceback (most recent call last): File "setup.py", line 131, in <module&gt; ext_modules=get_libcarla_extensions(), File "setup.py", line 91, in get_libcarla_extensions libs = [x for x in os.listdir('dependencies/lib') if any(d in x for d in required_libs)] FileNotFoundError: [WinError 3] The system cannot find the path specified: 'dependencies/lib'
 
Could it be related?
  
Its been a few years but did you find way to solve this?

**Comment by dhruv-g334** [comment]
> Hi @xuyanwen2012 , I faced the same problem and managed to get around it. After compiling Carla client and server, instead of "make PythonAPI", I did:
> 
> cd PythonAPI/carla python setup.py install
> 
> This generated the /dist folder and the ".egg" file within. I am able to run the .py examples now. Hope this helps in your case.

I am still facing the dependencies error. The dependencies folder is still not created.

**Comment by Nighttell** [comment]
@dhruv-g334 Do you know how to solve it now?i met it today  :(

**Comment by ixfd64** [comment]
> > I'm also getting an error, although it's not the same.
> > `Traceback (most recent call last): File "setup.py", line 131, in <module> ext_modules=get_libcarla_extensions(), File "setup.py", line 91, in get_libcarla_extensions libs = [x for x in os.listdir('dependencies/lib') if any(d in x for d in required_libs)] FileNotFoundError: [WinError 3] The system cannot find the path specified: 'dependencies/lib'`
> > Could it be related?
> 
> @ixfd64 Its been a few years but did you find way to solve this?

I don't remember the exact details as it's been a while. However, I think the issue went away for me after I upgraded to the latest release several months later.

**Comment by Zainab-Saka** [comment]
hi @ixfd64 I have this same issue. How did you fix it Please?
