### ISSUE TITLE
carla/docs issues

### ISSUE THREAD

**Issue by robogast** [carla-simulator/carla#2476]
Currently, there are some issues with the documentation, as present in `master` (currently at commit 386011d):
- URLs frequently are broken
- Spacing/markup is broken 

The reason these issues are present is (as far as I can tell) two-fold, and should be relatively easy to fix:
1. A lot of urls points to files which exist in the repository, but are linked wrong (e.g. `../img` instead of `./img`. Or; urls point to `carla/<file>` instead of `carla/Docs/<file>.md` (both `/Docs/` and `.md` are needed). See for example my edits in #2469). 
1. The usage of `html` markup messes in some places with the markdown (i.e. GitHub) markup. Example: In the file `python_api` contains a lot of spots where a `html` header is followed immediately by a list. This doesn't work: the `html` header should be followed by an empty line, and then followed by the markdown list.

I think this is the responsibility of @fdomf?

I'm willing to fix these links and make a PR myself, but I need to know if these error are not the result of some automatic doc gen script.

**Comment by fdomf** [comment]
Hello Robogast.
First of all, thank you for your contribution!

About the first point. I believe that the use of `../` is working instead of `./` or at least it was before when I wrote those paths. 
I think that the problem was that the usage of `./` worked in our test environment, but when it was deployed it did no longer work, instead, using `../` worked.

The same happens in #2469 as the `[custommaplink]: /dev/map_customization` is wrong and should be like this: `[custommaplink]: ../dev/map_customization`.

I could be mistaken about the usage of the paths/files, unfortunately, I cannot check it properly right now.

As for the second point, the `python_api` is automatically generated by a [python script](https://github.com/carla-simulator/carla/blob/master/PythonAPI/docs/doc_gen.py), maybe it was not taken into account when it was done, I believe it can be modified to meet the standards.

Once again, thank you for your time and contribution!

@marcgpuig  @sergi-e
