### ISSUE TITLE
Problem with PythonAPI while building CARLA 0.9.8

### ISSUE THREAD

**Issue by Julian9875** [carla-simulator/carla#2585]
Hello, I've been trying to build CARLA. But I have encountered many problems. Right now, I have a problem with make Python API. I've been trying to build for every version since 0.9.5. Now with this 0.9.8 version this problem it is supposed to be solved, but I still have this problem:

![image](https://user-images.githubusercontent.com/43647876/76542571-30ae1680-6453-11ea-805c-e903b84b5dbd.png)

How could I resolve this problem? Thanks in advance :)

I am using:
Windows 10
Python 3.7.3
x64 Native Tools for VS 2017
Unreal Engine 4.22.3
GNU make 3.81
Cmake 3.14.0-rc4

**Comment by OnTheStormx** [comment]
Hi @Julian9875 Did u find the solution.

**Comment by Julian9875** [comment]
Unfortunately no, I installed Ubuntu to make it work, but I still need it in Windows :(

**Comment by carfloresp** [comment]
Hi @Julian9875, I faced the same problem and managed to get around it. After compiling Carla client and server, instead of "make PythonAPI", I did:

cd PythonAPI/carla
python setup.py install

This generates /dist folder and the ".egg" file within. I am able to run the .py examples now.
Hope this helps.
