### ISSUE TITLE
Why using FDataStream instead of FDataMultiStream for sensors?

### ISSUE THREAD

**Issue by wx9698** [carla-simulator/carla#2597]
As titled. I change the data type of the carla sensor's stream to FDataMultiStream, recompile the package and thus I can use two clients' scripts to listen to the same sensor and get the same images. Why still using FDataStream for sensors? Are there any other concerns? I think using FDataMultiStream will bring more functionalities and allow people listen to the same sensor. Thank you!

**Comment by wx9698** [comment]
And also, I see the changes to FDataMultiStream in this PR https://github.com/carla-simulator/carla/pull/915. In the section of "Other C++ improvements". Why still keeping FDataStream there?

**Comment by sergi-e** [comment]
I am pinning @nsubiron, because maybe he knows something about this specific issue.

**Comment by nsubiron** [comment]
Streams are a bit faster than multi-streams. Streams are lock-free while multi-streams get a lock and iterate a list of clients. This part was carefully optimized because, for cameras, this is executed in the render thread (usually the bottleneck), thus any tiny gain here contributes to overall performance.

It's a tiny performance improvement only measurable in the streaming benchmarks, I imagine not at all noticeable in the common use cases, but that's why at the time I didn't change all the sensors to multi-streams.

**Comment by wx9698** [comment]
I see, thank for the explanation. So I guess you are still going to keep it there without any change?

**Comment by nsubiron** [comment]
Try raising the issue with the core team if you think is better to use multistreams (I'm no longer working for Carla). I would do some benchmarks too, low resolution images, lidar in no-rendering mode, those are some use cases that could get worse performance if any. Also check if this affects frame drops, that's a real issue in sync mode as currently may cause dead-locks.

**Comment by wx9698** [comment]
Thank you!
