### ISSUE TITLE
Carla PythonClient/manual_control.py problems

### ISSUE THREAD

**Issue by YashBansod** [carla-simulator/carla#260]
I downloaded the latest master repository and built it from source. I packaged the game for Linux and then started it in server mode:
`./CarlaUE4.sh /Game/Maps/Town01 -carla-server -windowed -ResX=640 -ResY=480 -benchmark -fps=25`
Then I ran the **manual_control.py** in the source code I cloned from GIT.

I see that the main window created by the carla server keeps flickering if it was opened in a different resolution than that specified in the camera settings of manual_control.py. 
This is the message I get in the terminal.
![terminal](https://user-images.githubusercontent.com/16332426/36932636-cfcf33d8-1ef1-11e8-8ac1-586e1c7848d7.png)

Although this doesn't create any problems since the view in the main window is not really used anywhere, I see a 2 - 3 FPS drop in performance because of this. It also means that the server now has to render the output at a resolution specified in the client code. So, if I set my cameras for 1920x1080, my server also has to run at the same resolution. This uses the precious Compute and GPU memory, which can be better used elsewhere.

**Comment by juaxix** [comment]
Hello @YashBansod , take a look to the [SceneCaptureCamera.cpp](https://github.com/carla-simulator/carla/blob/master/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureCamera.cpp#L100) when the UTextureRenderTarget2D* CaptureRenderTarget is created it uses the InitCustomFormat with the size in width and height (sizex and sizey), and this is where the render target texture is allocating memory, so it's normal and it's not rendering a 1920x1080 viewport (that's only for your screen resolution in your scene camera render, not ASceneCaptureCamera). 
You can also take a look to the unreal engine code for UnrealEngine_4.18/Engine/Source/Runtime/Renderer/Private/PostProcess/SceneRenderTargets.cpp:
```
if( (BufferSize.X != DesiredBufferSize.X) ||
                (BufferSize.Y != DesiredBufferSize.Y) ||
                (CurrentGBufferFormat != GBufferFormat) ||
                (CurrentSceneColorFormat != SceneColorFormat) ||
                (CurrentMobileSceneColorFormat != MobileSceneColorFormat) ||
                (bAllowStaticLighting != bNewAllowStaticLighting) ||
                (bUseDownsizedOcclusionQueries != bDownsampledOcclusionQueries) ||
                (CurrentMaxShadowResolution != MaxShadowResolution) ||
                (CurrentRSMResolution != RSMResolution) ||
                (CurrentTranslucencyLightingVolumeDim != TranslucencyLightingVolumeDim) ||
                (CurrentMobile32bpp != Mobile32bpp) ||
                (CurrentMSAACount != MSAACount) ||
                (bCurrentLightPropagationVolume != bLightPropagationVolume) ||
                (CurrentMinShadowResolution != MinShadowResolution))
        {
                CurrentGBufferFormat = GBufferFormat;
                CurrentSceneColorFormat = SceneColorFormat;
                CurrentMobileSceneColorFormat = MobileSceneColorFormat;
                bAllowStaticLighting = bNewAllowStaticLighting;
                bUseDownsizedOcclusionQueries = bDownsampledOcclusionQueries;
                CurrentMaxShadowResolution = MaxShadowResolution;
                CurrentRSMResolution = RSMResolution;
                CurrentTranslucencyLightingVolumeDim = TranslucencyLightingVolumeDim;
                CurrentMobile32bpp = Mobile32bpp;
                CurrentMSAACount = MSAACount;
                CurrentMinShadowResolution = MinShadowResolution;
                bCurrentLightPropagationVolume = bLightPropagationVolume;

                // Reinitialize the render targets for the given size.
                SetBufferSize(DesiredBufferSize.X, DesiredBufferSize.Y);

                UE_LOG(LogRenderer, Log, TEXT("Reallocating scene render targets to support %ux%u Format %u NumSamples %u (Frame:%u)."), BufferSize.X, BufferSize.Y, (uint32)GetSceneColorFormat(), CurrentMSAACount, ViewFamily.FrameNumber);

                UpdateRHI();
        }
```

Notice that when there is a change in the scene related to color, shadows, msa, lights or other things that triggers the regeneration of the render texture, it will allocate memory again, check also that the engine will try to reuse the same resource so even when you restart an episode, it will not allocate the render texture again.

Ah, because vsync you may drop some fps but not all the time. Because of this depends on your GPU manufacturer's driver, and also settings such as r.vsync it is the reason why they wont support dynamic resolutions for UE4.19.
Regards,
Juan
