### ISSUE TITLE
RSS does not compile

### ISSUE THREAD

**Issue by gitmaster3000** [carla-simulator/carla#2665]
Hi,
after multiple cleanups, remakes and complete build from scratch I cannot get rid of the error.

"sensor.rss not found, please recompile with Python.rss" can someone please explain why this is happening and how I can fix it?

Ubuntu: 19
Carla: 0.9.8
Python: 3.6

Much Regards,
Ali

**Comment by gitmaster3000** [comment]
Bump

**Comment by mrwesleycrusher** [comment]
The error code is pretty self-explanatory, especially if you have read the docs for the intel rss portions of CARLA. Intel's rss features in CARLA are distributed under LGPL. CARLA is distributed under a MIT license. This causes a conflict due to the copy-left of the LGPL. Intel only wants RSS to be used for research, so thats why it is LGPLed. 

Now, in order to get the RSS features in CARLA, you are going to need to switch away from Ubuntu 19 down to Ubuntu 16 (with a possible migration to 18 coming soon), go and take a look at https://github.com/intel/ad-rss-lib, build all that stuff, and then, once it is built, build CARLA from source with the RSS features enabled. then it should all work nice and dandy.
