### ISSUE TITLE
No pedestrian/vehicle collision at relatively slow speed

### ISSUE THREAD

**Issue by ShahriarSefati** [carla-simulator/carla#2768]
Hi,

At slow speeds (~10 km/h), vehicles tend to push the pedestrians away rather than colliding with them. This behavior persists until a certain point where the collision is detected (examples attached.)

In case of the Crossbike model, the problem seems to be even worse (no collision at ~15 km/h). Is there a way to fix this behavior?

Issue #13 is related but I assume a lot has changed since that issue was opened. 
Currently using Carla 0.9.8 on Ubuntu 18.04.

Thanks!

![pedestrian-car-no-collision-1](https://user-images.githubusercontent.com/10872554/79795198-8f539380-8321-11ea-998a-9873db9f82a1.gif)

![pedestrian-bike-no-collision](https://user-images.githubusercontent.com/10872554/79794880-09374d00-8321-11ea-9ef8-365fc12b6731.gif)

**Comment by germanros1987** [comment]
This is critical and needs a quick fix @jackbart94 @Axel1092

**Comment by bernatx** [comment]
The problem is that it feels unrealistic because the pedestrian has not the animation that moves apart from the vehicle. We need to fix that behaviour, first the pedestrians have so many colliding boxes and we need to remove some of them. Then, we will try to fine tune the pedestrian avoiding strategy to make it more realistic.

**Comment by KasraMokhtari2112** [comment]
Hi, I am experiencing exactly the same issue #3183. Since I am doing RL on pedestrian-ego vehicle collision, this is absolutely important to get an accurate feedback from the collision sensor. I really appreciate it if you guys can work on this issue. Thanks a lot. 
@ShahriarSefati Did you find a way to work around this issue?

**Comment by Alby407** [comment]
There was this merge last year: https://github.com/carla-simulator/carla/pull/1183/files
But is not really a "pedestrian collision sensor", because it will check within a radius, which is not necessarily the bounding box of the ego vehicle. You have to tune it manually.

> The problem is that it feels unrealistic because the pedestrian has not the animation that moves apart from the vehicle. We need to fix that behaviour, first the pedestrians have so many colliding boxes and we need to remove some of them. Then, we will try to fine tune the pedestrian avoiding strategy to make it more realistic.

It's still required, even if pedestrians get pushed away. The collision should be detected at least.

**Comment by gaoyinfeng** [comment]
Is this bug fixed?

**Comment by truncs** [comment]
@bernatx  Let's say that there is an animation for pedestrians and they have a good strategy for avoidance, would this still happen at low vehicle speeds if the vehicle manages to hit the pedestrians?
I feel that there should be a configurable option in the sensor that allows for a stricter definition of a collision.
