### ISSUE TITLE
Error with spawn_npc.py in created map

### ISSUE THREAD

**Issue by eloy96vg** [carla-simulator/carla#2802]
Hi, i have a map created in RoadRunner and in previous releases the vehicles navigation worked perfect with scripts like manual_control.py and spawn_npc.py. Now, with new releases vehicles don't follow their paths and navigate randomly. I know that there is a new system (Traffic manager) that replaces autopilot, but i don't know what to do. I attach two visual photos of the problem.

What could i do to solve this problem and vehicles can navigate correctly?

Thanks in advance.
<img width="1003" alt="Captura de pantalla 2020-04-30 a las 13 39 05" src="https://user-images.githubusercontent.com/47063072/80706148-181fbb80-8ae8-11ea-948a-dd2319866e00.png">
<img width="1001" alt="Captura de pantalla 2020-04-30 a las 13 39 35" src="https://user-images.githubusercontent.com/47063072/80706160-1bb34280-8ae8-11ea-8ba1-794a55e5e717.png">

**Comment by jackbart94** [comment]
Hi,

Unfortunately, with Traffic Manager replacing the former Autopilot since 0.9.7, the map creating process has changed. Things like the RoutePlanner are now deprecated, we only use the information coming from OpenDrive.

Here's [how to create a map for versions after 0.9.7](https://carla.readthedocs.io/en/latest/tuto_A_add_map/#add-a-new-map), let me know if it helps you!
