### ISSUE TITLE
Visualize Lane Markings in OpenDrive Standalone Mode

### ISSUE THREAD

**Issue by ghost** [carla-simulator/carla#2829]
Currently, with version 0.9.9, the OpenDrive standalone mode does not visualize lane markings (e.g. see following image from the [release notes](https://carla.org/2020/04/22/release-0.9.9/) ).

Can they be added? This increases the number of usecases CARLA could be used for. Also it eases transitioning from any other simulator to CARLA, as many other tools already have support of OpenDRIVE. So transferring assets from any other simulator to CARLA would get easier.

![image](https://user-images.githubusercontent.com/720488/81393074-f9d94180-911f-11ea-8fc4-3bd743ed0141.png)

**Comment by germanros1987** [comment]
The lane markings are there, but not rendered. We will add them in future versions of the tool.

**Comment by marcgpuig** [comment]
Yes, this is in our roadmap. the main difficulties here are how to generate these LaneMarkings as separate meshes of the main road so they can be also added into the semantic segmentation rendering. Since we also want to change how the semantic segmentation works, we must wait until it's completely done so _maybe_ the separation of these meshes will not be necessary.

**Comment by Kin-Zhang** [comment]
Is there any update?

**Comment by soup1997** [comment]
Is there any progress on this? please let me know.

**Comment by rebolomo** [comment]
Is there any update? please let me know.
