### ISSUE TITLE
check if the walker is on the crosswalk.

### ISSUE THREAD

**Issue by yousinf** [carla-simulator/carla#2830]
Hi, 
How can I check if a walker cross the street on a crosswalk or not??

Thanks.

**Comment by yousinf** [comment]
I need help, SOS.

**Comment by germanros1987** [comment]
@yousinf could you please elaborate a bit more?

**Comment by bernatx** [comment]
Hi, currently we don't have that exposed. Probably wouldn't be too hard to expose that in property of the pedestrian that you can check in which kind of zone the pedestrian is walking (road, sidewalk, crosswalk or grass). Because that is done by the client there is no performance problems. I will add this as a feature request.
