### ISSUE TITLE
How can i get radar resolution in Carla?

### ISSUE THREAD

**Issue by kannidekan** [carla-simulator/carla#2960]
Is the radar resolution available in Carla? I can't find it anywhere.
Please tell me how can i get it, thanks very much!

**Comment by germanros1987** [comment]
@kannidekan that concept does not apply to our "radar" because the data generated by the radar is not given in a "per-object" way. In other words, the radar is not attempting to differentiate between multiple targets. Instead, it is providing information about multiple locations that could correspond to the same target (object).

**Comment by kannidekan** [comment]
@germanros1987 Ok, i got it. Thanks very much!
