### ISSUE TITLE
details about collisions on carla-0.9.9

### ISSUE THREAD

**Issue by whuxhzhang** [carla-simulator/carla#3050]
Can Carla record more details about the collision, such as whether my car hit someone else or someone else hit my car

**Comment by germanros1987** [comment]
Hi @whuxhzhang 

Our goal in designing the recording system was to provide the minimum information that is needed in order to detect all possible events. However, we didn't plan to record all these events by default. You could parse the log and generate that information to assign responsibility to the right vehicle. 

Hope this helps.

**Comment by whuxhzhang** [comment]
> Hi @whuxhzhang
> 
> Our goal in designing the recording system was to provide the minimum information that is needed in order to detect all possible events. However, we didn't plan to record all these events by default. You could parse the log and generate that information to assign responsibility to the right vehicle.
> 
> Hope this helps.

Thanks for your replay. But where can I find the log ？

**Comment by germanros1987** [comment]
https://carla.readthedocs.io/en/latest/adv_recorder/
