### ISSUE TITLE
TrafficManager "set_percentage_keep_right_rule" has no effect on traffic behaviour

### ISSUE THREAD

**Issue by philowaddell** [carla-simulator/carla#3060]
CARLA version: 0.9.9.4
OS: Windows 10

This function appears in "LibCarla/source/carla/trafficmanager/Parameters.h" and is renamed in "PythonAPI/carla/source/libcarla/TrafficManager.cpp". No documentation appears for this funtion at: https://carla.readthedocs.io/en/latest/python_api/#carlatrafficmanager, however it is mentioned in a recent webinar: https://www.youtube.com/watch?v=n9cufaJ17eA&t=140s (Slide 8)

Setting the value anywhere between -100 and 100 (similarly to how speed is controlled) seems to have no effect on traffic behaviour: cars continue to drive in the middle/outside lane when on clear stretches of road; cars overtake on the wrong side; cars also fail to overtake when stuck behind a slow moving vehicle.

Any suggestions as to why this may be, or how to fix it?

**Comment by jackbart94** [comment]
Hi,

The value goes from 0 (no chance of doing it) to 100 (always keep on the most right lane). However, we have a revamping of this parameter scheduled, with others too.

Having said this, cars do normally drive in middle/outside lanes, they do overtake on both sides, and they sometimes don't overtake due to curvature of the road or other cars incoming. We will add more parameters to change this too.

If you want to change how the traffic behaves, you can take a look into the Traffic Manager code and maybe even implementing such things!
