### ISSUE TITLE
Is it possible to run carla with UnrealEngine 4.25 ?

### ISSUE THREAD

**Issue by SimonLeeGit** [carla-simulator/carla#3214]
Hi, I want to use some features in UnrealEngine 4.25. Is it possible to build carla with UnrealEngine 4.25?

**Comment by germanros1987** [comment]
@SimonLeeGit if you are willing to dedicate the time and effort I don't see why not, but we don't provide support for that yet.

**Comment by qhaas** [comment]
I just tried with 0.9.11 and UE 4.25.4, it will require some work:
```
error: no member named 'GameDir' in 'FPaths'
...
error: no member named 'AutoExposureCalibrationConstant' in 'FPostProcessSettings'
...
 error: non-const lvalue reference to type 'TArray<[...], TSizedDefaultAllocator<32>>' cannot bind to a value of unrelated type 'TArray<[...], TSizedDefaultAllocator<64>>'
```

**Comment by qhaas** [comment]
I have a rough first cut at getting CARLA 0.9.11 building/running with UE 4.25.4, simply apply the attached patch to a carla 0.9.11 tag checkout and compile CARLA using an official UE 4.25.4 release.  Note that I am not part of the CARLA team, this is not a supported configuration, I haven't fully tested it, and most importantly, getting it building/running isn't nearly as heavy of a lift as it would be for @germanros1987 's team to do a proper quality assurance (QA) and change to their continuous integration (CI).

This also seems to allow headless rendering with no x-server with Vulkan, per Issue #3800 .  Also, thanks to [issue 3758](https://github.com/carla-simulator/carla/issues/3758#issuecomment-754231220) for a fix to the packaging process, which is also included.

Run with `./CarlaUE4.sh -RenderOffscreen -vulkan` for headless vulkan mode.

[carla0.9.11_ue4.25.4.txt](https://github.com/carla-simulator/carla/files/5888077/carla0.9.11_ue4.25.4.txt)
![carla_headless_vulkan](https://user-images.githubusercontent.com/34581474/106155568-d2fbe900-614e-11eb-8fad-d5185088ca10.png)

**Comment by jimmyw404** [comment]
> I have a rough first cut at getting CARLA 0.9.11 building/running with UE 4.25.4, simply apply the attached patch to a carla 0.9.11 tag checkout and compile CARLA using an official UE 4.25.4 release. Note that I am not part of the CARLA team, this is not a supported configuration, I haven't fully tested it, and most importantly, getting it building/running isn't nearly as heavy of a lift as it would be for @germanros1987 's team to do a proper quality assurance (QA) and change to their continuous integration (CI).

Nice job, @qhaas , I'd be curious to hear if you have any further issues after getting some runtime on your patched version. I'm also curious, have you looked into performing the same kind of upgrade to 4.26 and do you think it would be similar in scope?

**Comment by qhaas** [comment]
So far, so good.  I ran 8 such instances (CARLA 0.9.11 + UE 4.25.4 + Vulkan Headless (no-X server), one per GPU) on our [DGX A100](https://www.nvidia.com/en-us/data-center/dgx-a100/) for about 8 hours with Town03, several weather conditions, and RGB cameras.  That is allot of data to examine, but so far spot checking hasn't shown any anomalies and it did not crash, produce unexpected warnings/errors, etc.  My biggest worry is copying that TArray64 into a TArray, likely should add an assert in there to catch any overflows.

UE 4.26 will likely be trickier, note in my patch file some of the functions got a `DEPRECATED` suffix, those might have gone away with UE 4.26 (haven't checked).  I didn't go further than UE 4.25.4 because all we needed was the ability to confirm headless vulkan without X worked with CARLA when using that version of UE, which it does!

I once ported an earlier version of CARLA that was meant for [UE 4.22 to UE4.23](https://github.com/carla-simulator/carla/issues/1567#issuecomment-700790499), this was a much easier, didn't even have to tweak blueprints with the UnrealEditor.

**Comment by qhaas** [comment]
For those dropping into this issue, [the contributors report CARLA 0.9.12 will target UE 4.26.x](https://github.com/carla-simulator/carla/issues/3865#issuecomment-777357195)

**Comment by amancodeblast** [comment]
I am not able to run Carla 0.9.12 headless on the A100 server (Ubuntu 20.04). 
I used the command ` ./CarlaUE4.sh -RenderOffScreen`  
I didn't install UE4 as I don't have to render maps. Do we really need UE4  to run headless Carla?
Any help is appreciated.
