### ISSUE TITLE
[Testing]  (New colliders of Vehicles)

### ISSUE THREAD

**Issue by XGodina** [carla-simulator/carla#3281]
In order to test all collider of vehicles are work fine

Content_version 20200908_3f92e51.tar.gz

**Comment by DSantosO** [comment]
Great work!
The general driving of all cars has improved a lot and I think they are more manageable and realistic. 

Anyway, there are some issues:
- the general behavior of motorcycles are quite bad. For example:
   - yamaha: it presents weird jumps suddenly when driving like they were detecting potholes. Also, present a hard wheelie when braking. 
   - ninja: fewer jumps when driving but it does present wheelie when braking. Also weirds oscillations when turning at moderate speed. 
- Cars behave generally well but they still have some minor issues:
  - t2: I think it presents some over-steering. Also, it overturns very easily (this I am not sure is an error because of the shape of the vehicle)
  - Etron: (reported by @marcgpuig) problem with the position of the skeleton.
  - Grandtourer: it presents high over-steering
  - Mini: it presents high over-steering, very dificult to drive.

**Comment by XGodina** [comment]
Thanks for you report @DSantosO 

Now, the issus about cars you reported are fixed. We are working to fix problems with behavior of motorcycles and bikes. MeanWhile we add the new values of suspension for all cars. Suspension has been divided into 5 categories
Coupe: Lincoln, Seat Leon, Tesla, Mercedes Benz Coupe and Audi TT
Urban: Mini, C3, Mustang, Audie A2, Chevrolet Impala, Prius, Micra, Isetta, Dodge, Tourier
OffRoad: Cybertruck, Jeep, Patrol and Audi Etron
Truck : Carla Cola
Van: VolskWagen T2

Please guys, tested and report it.

**Comment by joel-mb** [comment]
Hi!
Overall, the behaviour of the vehicles is good.
Some comments:

**Motorbikes and bikes**
I know this is a known issue. Motorbikes and bikes have weird behaviour and it's very difficult to turn. They are like always "colliding". 

As an additional note, `vehicle.gazelle.omafiets` is much faster than the other bikes (35km/h vs 18km/h)

**Police**
The police vehicle feels very weird for me when turning.

Also, I've detected that some vehicles have, in my opinion, small maximum velocities:
`vehicle.toyota.prius`. Maximum velocity: 68km/h
`vehicle.mustang.mustang`. Maximum velocity: 100km/h

**Comment by XGodina** [comment]
Hi,

**Motorbikes and bicycles**
- The new colliders and suspension are already in the master. The problem was that the old collider touched the ground and because they behaved strangely
- Too, we adjusted the center of mass. This prevents the vheícules from getting up when braking.

I'm going to look at the police car and the bike. I'll be reporting

**Comment by XGodina** [comment]
Hi,

Motorbikes and bicycles
So far we have focused on collisions, massa center and suspensions. 
The behavior has improved a lot, the engine theme and speeds will be adjusted later.
