### ISSUE TITLE
[Testing] Autoexposure & Lights intensities

### ISSUE THREAD

**Issue by Madecu** [carla-simulator/carla#3340]
We have changed the default exposure mode to autoexposure (Eye adapting).
We also have changed the values of streetlights, car lights, and buildings.

We have to drive around all the maps, changing between day and night, to see if there are some lights that are not lighting properly (too bright or too low). Including all the vehicle lights (breaks, reverse, high beam, blinkers, etc.).

While you are testing that, look out for some artifacts or weird behaviors from the autoexposure. Just in case.

**Comment by Axel1092** [comment]
Lightning seems ok and autoexposure works well, most areas are properly lit except when there are no lights (which is ok). Only  in Town03 this area seems too dark but this might be intentional.
![image](https://user-images.githubusercontent.com/35765780/94025038-5def6000-fdb8-11ea-8b1c-b45f479f3659.png)

**Comment by Madecu** [comment]
- Fixed weird artifacts with the clouds (Turn blue or turn the sky into pitch black)

- Tweaked "Fountain", "FoodCar", "CarlaCola" and "BusStop" light intensities.

- Lowered Skyscraper_04 light intensity

- Changed mustang back blinkers

- Increased spotlight radius in streetlights (simulates global lighting). Now they light further
