### ISSUE TITLE
Differ lane types by colors

### ISSUE THREAD

**Issue by italovinicius18** [carla-simulator/carla#3346]
I'm trying to mine some data to run a lanenet model on CARLA images, but i have to differ lanes types like broken and solid lines. I already used semantic and rgb camera sensor to get images and i filter the image just to focus on lines, but how i can i differ the color the types of lanes ? I need to use waypoint and waypoint.lane_type ? But how i can apply these to differ the color lanes in image to generate the ground truth data ?

**Raw image:** ![232965](https://user-images.githubusercontent.com/39673124/93926238-a68e1700-fced-11ea-83d9-8eb986286d33.png)

**Filtered image:** ![232964_lane](https://user-images.githubusercontent.com/39673124/93926257-aa219e00-fced-11ea-915b-33e961cc6177.jpg)  

I want that broken lines have a diferent color,it's that but i dont know how to do that

**Comment by germanros1987** [comment]
@marcgpuig what would be the simples method to achieve this?

**Comment by Madecu** [comment]
Hi @italovinicius18, as far as I know, unfortunately, this is a hard task due to the way RoadRunner gave us the geometry of the lines and roads. To do so, you would need to export all the road lines meshes from unreal and open them with some 3D software such as Maya or 3DsMax. Then, you need to detach the solid lines from the broken ones and import them again into unreal engine. Once you have separated both types of lines in their folders, you have to put them inside the scene at the same location as before. Finally, you have to edit open3d_lidar.py and add the new semantic segmentation categories and assign them a color.

**Comment by italovinicius18** [comment]
Thank for the aswer @Madecu
