### ISSUE TITLE
Enum comparison in behavior_agent fails even if True

### ISSUE THREAD

**Issue by t27** [carla-simulator/carla#3462]
This is regarding the enum comparisons in the behavior_agent here, https://github.com/carla-simulator/carla/blob/31fff28bc6d24ddae0b3977f8ac343ed16019202/PythonAPI/carla/agents/navigation/behavior_agent.py#L271

I am on Python 3.7 and Carla 0.9.9.4, 

The enum comparison doesnt work directly,

for example `self.direction == RoadOption.LANEFOLLOW` on line 286 is always `False`, even if the direction is indeed `LANEFOLLOW`

I have to use the `.value` attribute of the enum to ensure it works correctly,

Here's a screenshot from my debugging console,

![image](https://user-images.githubusercontent.com/2003371/96297225-8a188e00-0fbe-11eb-9d94-0158bc3241d5.png)

**Comment by glopezdiest** [comment]
Hey @t27. I'm using Python 3.6 and CARLA 0.9.10.1 and that check is indeed failing. However, CARLA also has that type of checks at the *global_route_planner* and the ScenarioRunner repository, and this isn't happening in any of those cases.

We'll take a look at it. Also, I'm tagging @jackbart94 .

**Comment by raymanfx** [comment]
I noticed this issue as well. The behavior agent is completely broken in all recent CARLA releases due to this.
My workaround:

Remove the `RoadOption` class from `PythonAPI/carla/agents/navigation/local_planner_behavior` and import that enum from the `local_planner.py` class instead:

`from agents.navigation.local_planner import RoadOption`

**Comment by germanros1987** [comment]
@glopezdiest could you please work on fixing this?

**Comment by glopezdiest** [comment]
Yes, indeed
