### ISSUE TITLE
Several buildings have multiple bounding boxes

### ISSUE THREAD

**Issue by ARSekkat** [carla-simulator/carla#3488]
I projected the nearby buildings bounding boxes of the vehicle, and as shown in the image attached the same building have multiple bounding boxes, it's the case in Town10HD too. Is this on purpose?
Ubuntu 18.04.5 LTS
CARLA 0.9.10.1 

![screenshot](https://user-images.githubusercontent.com/18660798/96631191-4d2dfd80-1316-11eb-85a4-c69d26dc2366.png)

**Comment by Madecu** [comment]
Hi @ARSekkat, this happens because we built those buildings as procedurals, where we have different "pieces" of the building so we can create different shapes with the same meshes. So every bounding box you see, it is the bounding box of that particular "piece".
We use this method almost entirely to build Town10HD.

![BuildingPieces](https://user-images.githubusercontent.com/54811869/96708016-ed2c6b00-1398-11eb-9620-c9621afbe458.jpg)

**Comment by ARSekkat** [comment]
Hello @Madecu, Thank you for your answer.
Is there a way to have one bounding box for each building?

**Comment by Madecu** [comment]
Well, it is more complex than it seems. If we have the bounding box from the 'group of meshes', depending on the shape of the building, it will have a lot of empty spaces. There are also other assets inside those 'groups' that will cause an inaccurate bounding box.
We are currently working on the information sent back from the bounding boxes. We will study the possibility of implementing it in these cases.

**Comment by ARSekkat** [comment]
Ok, thank you.
