### ISSUE TITLE
Hello CARLA Team, I wanted to change the vehicle dimensions to some other values and wanted to control the velocity in autopilot mode...Please help me doing it. (I am new to CARLA)

### ISSUE THREAD

**Issue by Sujit-kamat** [carla-simulator/carla#3500]

**Comment by XGodina** [comment]
Hi, well maybe if you review our documentation you have some ideas on how to do it. Carla.org. However, change the vehicle dimension It's no easy. @gsmario could you give him some ways to do it, please.

**Comment by gsmario** [comment]
Hello @Sujit-kamat in order to change the vehicle dimensions, you need to open the 3d model in a 3d software.
Then you need to remove the rig/skin weights and after that you can scale the vehicle.
Remember to rig the vehicle to the skeleton again, adjusting the bones to the new wheels/vehicle position.
Reimport your new model in to unreal engine and test it :)
