### ISSUE TITLE
Carla Remote Connection Display

### ISSUE THREAD

**Issue by FarukOzderim** [carla-simulator/carla#3583]
Hello guys, did any of you successfully run Carla with remote connection?

I can run Carla without display and test examples, however I can not run Carla with display. I use aws instance with nomachine remote connection. Here are my results:
I think I take opengl errors, but my video driver should support opengl..

![image](https://user-images.githubusercontent.com/44067394/99026516-2f059700-257c-11eb-89dd-c28a950c6e3b.png)

**Comment by walzimmer** [comment]
Hi Faruk, 

seems like you have OpenGL 3.1 installed. Try running it with the -opengl3 flag:

CarlaUE4.sh -opengl3

Best,
Walter

**Comment by FarukOzderim** [comment]
Hello @walzimmer , I have used -opengl3 flag in the second image.

**Comment by walzimmer** [comment]
Then install OpenGL 4 and run it with the `-opengl` flag:
`$sudo apt install mesa-utils`

**Comment by grvbhosale** [comment]
Did you get it to work ? I am facing the same problem

**Comment by FarukOzderim** [comment]
No I haven't. It seems there is no one who solved this issue.

**Comment by germanros1987** [comment]
Hi @FarukOzderim . I do run CARLA remotely via VNC. There are a few things to consider in order to do the right setup.

First, you need to run a X.org server in the remote node. 
On top of that you need an X-zero VNC server. This means a VNC server that doesn't bring its own X server. A good option is tigerVNC. The command to run the X0VNC server typically looks like this: 
```x0vncserver -Display=:0 -NeverShared -PollingCycle=75 -rfbauth=your_vnc_folder/.vnc/passwd```

This assumes you have an Xorg server running at :0

If you are planning on running the default graphics backend of CARLA (i.e. Vulkan). You would need to have the latest NVIDIA driver installed in the remote node, along with libvulkan.

Best regards.
