### ISSUE TITLE
How to remove all rider animations for 2 Wheeled vehicles ?

### ISSUE THREAD

**Issue by Anna492** [carla-simulator/carla#3785]
Hello Carla Team, I would like that all riders of two wheeled vehicles stay static without any animations. How can I remove all the animations of riders ? Thank you.

**Comment by XGodina** [comment]
Hi @Anna492,

I will take a look. As soon as possible I'll tell you something.

**Comment by Anna492** [comment]
Hello @XGodina, do you have any solution to this question? Thank you in advance.

**Comment by Madecu** [comment]
Hi @Anna492,

In order to enable the two wheels animations, you have to go inside CARLA's UnrealEngine project, find "BP_Base2wheeledNew", select the mesh and change the Anim Class to 'None'

![image](https://user-images.githubusercontent.com/54811869/107518970-ecba1900-6baf-11eb-87ef-b85514c0f93c.png)

**Comment by Anna492** [comment]
Thank you @Madecu.
