### ISSUE TITLE
Light rendering is weird, and Lane direction is incorrect from the map that I export from RoadRunner (CARLA 0.9.11)

### ISSUE THREAD

**Issue by siraphopp** [carla-simulator/carla#3877]
I draw a map in RoadRunner with setting left-hand traffic rule

, and I did "Map ingestion in a build from source" method from
[https://carla.readthedocs.io/en/latest/tuto_A_add_map/#map-ingestion-in-a-build-from-source](url)

Here is the result.

![image](https://user-images.githubusercontent.com/44414518/107601997-d4530880-6c5a-11eb-84bc-d714b92c35ce.png)

The light is weird. I encountered this issue once when I used CARLA version 0.9.10, but I followed this issue #3426 . It could fix that, but cannot fix with CARLA version 0.9.11

, and when I spawned a car with manual_control.py, and toggled autopilot. The car was driven in right lane, but I set left-hand traffic rule when I export map from RoadRunner

, and RoutePlanner lines were not connected at every junction.

**Comment by Madecu** [comment]
Hi @siraphopp, 

These shadows are caused by Mesh Distance Fields. We believe that because of having the road and lane marking separately, unreal engine makes a mess when calculating those shadows.

To remove them, you have to go to each mesh of road and lane marking and set the distance fields resolution scale to 0.0.

![image](https://user-images.githubusercontent.com/54811869/107758592-66c0de00-6d27-11eb-8ab9-0de996524f2b.png)

**Comment by siraphopp** [comment]
Hi @Madecu and thanks for your reply.

![image](https://user-images.githubusercontent.com/44414518/108016861-15c22a00-7046-11eb-8587-babd0a228f81.png)

The issue was fixed.
