### ISSUE TITLE
Fog rendering distance and black sky (0.9.11)

### ISSUE THREAD

**Issue by TimLued** [carla-simulator/carla#3995]
Hello,

is it possible to change the fog rendering distance in 0.9.11?
The following image shows how it looks in Unreal by using
environment.py --fog 100 --fogfalloff 2 --fogdist 0

![fog_rendering](https://user-images.githubusercontent.com/50456467/111463528-f4755c00-871f-11eb-96c1-5b6e623254d1.jpg)

I want it more like it is shown in
https://carla.readthedocs.io/en/latest/tuto_G_retrieve_data/#weather-setting
where the fog ist placed all over the map.

Also, can I switch off the darkening of the sky with fog levels over 40?

Best regards

**Comment by Madecu** [comment]
Hello @TimLued,

To increase the rendering distance, you have to open BP_Sky, select Exponential Height Fog and increase "View Distance" in VolumetricFog category

![image](https://user-images.githubusercontent.com/54811869/111497289-44b0e600-8741-11eb-80bd-2259b0eb1eac.png)

In order to disable the decrease of the sun intensity over the amount of fog, you have to edit BP_Weather, "LightsIntensity" functions and skip the part that says "Subtract Sun Intensity From Fog Density"

![image](https://user-images.githubusercontent.com/54811869/111498880-ab82cf00-8742-11eb-90d3-b1020ebf9b92.png)


I hope it helps

**Comment by TimLued** [comment]
Thank you @Madecu
That's exactly what I wanted.
