### ISSUE TITLE
Collision holds previous maximum value

### ISSUE THREAD

**Issue by jd730** [carla-simulator/carla#403]
Hi,

why collisions hold previous maximum value? Also, why a car can get collision on the offroad such as sidewalk? I think the second question is because of the first one. In other words, the car could get the collision when it crashes the boundary between road and sidewalk, and it holds this value ~k scale.

**Comment by felipecode** [comment]
Hey @jd730 
For the paper we analyse 
the signals and  try find peaks in difference over a certain time frame.
If the peaks are more than a threshold it is counted as a collision. Check more
in metrics. http://carla.readthedocs.io/en/latest/benchmark_metrics/

The decision to accumulate it in CARLA , on the other hand, was made
to eliminate the duration of the collision from the signal. Since the communication
with the client is asynchronous, even if you don't receive some message from the server
you could still recover the collision signal. If we sent the instantaneous collision any communication issue could make the client to not capture a collision signal, something quite bad ! 

Hope I answered your question .
