### ISSUE TITLE
Spawning small objects fall through roads at times

### ISSUE THREAD

**Issue by HeuristicOctopus** [carla-simulator/carla#4167]
If user has a small prop - (in my example .2m x .2m x .1m) and several instances are spawned above road or terrain - some of the instances do not collide with the road. From what I have seen thus far - it has something to do with the speed at which the object collides (or fails to collide) with the road/terrain. 

to reproduce - make a .2m x .2m x .1m prop with a mesh collider (UCX). spawn 10 approximately 1 meter above the road - with prop.set_simulate_physics(True). They'll all land correctly on the ground. 

Increase spawn height to 8m above the road - and you will start seeing some props falling through the road/terrain. 

LMK if you want a video of this.

**Comment by DSantosO** [comment]
Hello @HeuristicOctopus,
It seems a problem of Unreal to detect collisions for fast, small objects.
I have run some tests and it seems to be fixed by decreasing the physics substeps delta time. By default is set to `max_substep_delta_time=0.01` but for me it worked by reducing it to `max_substep_delta_time=0.005`. Depending on your simulation time delta, you would also need to increase the `settings.max_substeps`. Check [this](https://carla.readthedocs.io/en/0.9.11/adv_synchrony_timestep/#physics-substepping) for more information about this.
