### ISSUE TITLE
How to get a actor_id of a vehicle in the image from sensor.camera.rgb ?

### ISSUE THREAD

**Issue by SanggunLee** [carla-simulator/carla#4249]
Hi.

is there a way to get a actor_id of vehicle in the image from sensor.camera.rgb ?

I looked for it in the carla docs several times, but
I found that only way is using sensor.lidar.ray_cast_semantic that returns object_idx.

but I need to use only rgb camera.
Is there a way or should I add new function for it ?

I know that I can get actor_id from world info, but as I know, there are no actor_id in the data from sensor.camera.rgb

thanks in advance.

**Comment by DSantosO** [comment]
Hello @SanggunLee,
Right now it is not possible to get the id of the actor through a camera. Anyway, I can see a couple of ways in which you could do that.
 - You could modify (or create another) semantic segmentation camera to output the id in the form of colors instead of the tag information. This could be a bit tricky because you need to modify the server and also to codify correctly the ids as colors so you can recover the information but I'm principle it is possible.
 - The other possibility can be done directly in the client but require some processing. You can use the semantic lidar to identify the ids and then project the points into the RGB image and identify the ids coming from the semantic lidar to the pixels in the image. The projection of the point is done for the normal lidar in the example script 'lidar_to_camera.py' so you have something to start there.

**Comment by SanggunLee** [comment]
Hi. @DSantosO 

Thanks for your recommendation.

I will use semantic lidar + camera.

**Comment by chris-redfield** [comment]
Is there a better solution in 2023 ?
I am saving images from several cars and I need to identify each actor
can't do that now, as I need to use the sensor callback, and that contains only the image, not the actor id

**Comment by SanggunLee** [comment]
@chris-redfield 
I don't know because I don't use carla these days. Two years ago, I solved it using LiDAR.

**Comment by chris-redfield** [comment]
> @chris-redfield I don't know because I don't use carla these days. Two years ago, I solved it using LiDAR.

I did a very ugly hack and added the car code to the X dimension of the image resolution, this way you easily get the codes
tradeoff is you get irregular resolutions of the camera images, but that didn't matter to me
