### ISSUE TITLE
Fps lower after adding players

### ISSUE THREAD

**Issue by zjh6252007** [carla-simulator/carla#4289]
Hello everyone,
Now I'm doing a multiple driving test. I have a computer as server and another three as clients. When I connect with one player, the server fps down from 70 to 30. When I connect with two players, the fps down from 30-20. And with three players, the server fps down to 15. I guess that the increase in RGB cameras has led to a decrease in FPS. Is there any way I can improve the fps? 

I'm now using ubuntu 18.04.  CARLA 0.9.11

**Comment by qhaas** [comment]
According to the [carla performance report](https://carla.readthedocs.io/en/latest/adv_benchmarking/#carla-performance-report), adding vehicles does decrease performance significantly.  If they are managed by autopilot (traffic manager), performance decreases further, in part because [TM appears to be single-threaded](https://github.com/carla-simulator/carla/issues/3442#issuecomment-846634130) (cpu bound).

You can check to see if you are CPU or GPU bound by using `nvidia-smi` and `top` to compare GPU vs CPU if you are in no mood to profile the code.  If you see the python process pegged at 100% CPU, likely means you have a bottleneck with some feature that is single-threaded.

If you are GPU bound, [graphics performance tweaks](https://carla.readthedocs.io/en/latest/adv_rendering_options/#graphics-quality) might not help.

If you are CPU bound...  enabling [hybrid mode](https://carla.readthedocs.io/en/latest/adv_traffic_manager/#hybrid-physics-mode) can help with physics induced coy bottlenecks, depending on how many NPCs are in the simulation that are not near your players.  If you are saving imagery out as PNGs, [know libpng is single-threaded](https://github.com/carla-simulator/carla/issues/3895), but one can switch to tiff to mitigate.

Also, if you are using [synchronous mode](https://carla.readthedocs.io/en/latest/adv_synchrony_timestep/) with multiple clients, then you might be in uncharted performance territory ;)

**Comment by liuyandong1988** [comment]
> According to the [carla performance report](https://carla.readthedocs.io/en/latest/adv_benchmarking/#carla-performance-report), adding vehicles does decrease performance significantly. If they are managed by autopilot (traffic manager), performance decreases further, in part because [TM appears to be single-threaded](https://github.com/carla-simulator/carla/issues/3442#issuecomment-846634130) (cpu bound).
> 
> You can check to see if you are GPU or CPU bound by using `nvidia-smi` and `top` to compare GPU vs CPU if you are in no mood to profile the code. If you see the python process pegged at 100% CPU, likely means you have a bottleneck with some feature that is single-threaded.
> 
> If you are GPU bound, [graphics performance tweaks](https://carla.readthedocs.io/en/latest/adv_rendering_options/#graphics-quality) might help.
> 
> If you are CPU bound... enabling [hybrid mode](https://carla.readthedocs.io/en/latest/adv_traffic_manager/#hybrid-physics-mode) can help with physics induced coy bottlenecks, depending on how many NPCs are in the simulation that are not near your players. If you are saving imagery out as PNGs, [know libpng is single-threaded](https://github.com/carla-simulator/carla/issues/3895), but one can switch to tiff to mitigate.
> 
> Also, if you are using [synchronous mode](https://carla.readthedocs.io/en/latest/adv_synchrony_timestep/) with multiple clients, then you might be in uncharted performance territory ;)

I try the _hybrid mode_  method(fig 1). In the beginning, the fps is almost 10 fps(fig 2). However, the FPS also decreases after some episodes (fig 3). I use the synchronous mode, and server/client fps is 10. I set 50 vehicles and 50 pedestrains in Town02 (Carla 0.9.11). I have to restart my program script. This problem has bothered me for a long time.

![Screenshot from 2021-07-21 10-30-15](https://user-images.githubusercontent.com/21078728/126421685-076ab0c5-2946-40fe-b9e8-2a818cdb7c7a.png)
![Screenshot from 2021-07-21 10-31-10](https://user-images.githubusercontent.com/21078728/126421747-30c89638-0e98-4b93-a508-347ddc833e55.png)
![Screenshot from 2021-07-21 10-28-49](https://user-images.githubusercontent.com/21078728/126421793-393f7367-7d6e-4059-81d1-e69dd84bbcd7.png)
