### ISSUE TITLE
lidar_to_camera.py bug

### ISSUE THREAD

**Issue by helloworldunicon** [carla-simulator/carla#4366]
lidar_to_camera.py  
 
The output radar map, why is there a map of radar signal behind

**Comment by DSantosO** [comment]
Hello @helloworldunicon,
What do you mean? There are no radars in that script...

**Comment by helloworldunicon** [comment]
已经解决了 ，是调参测试的时候，每分钟的点数太少，会导致地图上某些位置 生成不了雷达数据，不过雷达的每分钟点数我调到1000000，会不会非常影响程序的效率。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "carla-simulator/carla"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月14日(星期三) 下午5:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [carla-simulator/carla] lidar_to_camera.py bug (#4366)





 
Hello @helloworldunicon,
 What do you mean? There are no radars in that script...

**Comment by DSantosO** [comment]
Hello @helloworldunicon,
Sorry about the late response.
I am glad that you solved it. 
About your question: yes, increasing the number of points affects greatly to the performance. 
This is difficult to say numbers because depends on the scenario and your hardware but it general duplicate the number of points per second duplicates the work so expect a drop in performance accordantly.

**Comment by helloworldunicon** [comment]
&nbsp;help？thankyou。
