### ISSUE TITLE
Obtaining deterministic RGB sensor output over multiple runs

### ISSUE THREAD

**Issue by pavanteja295** [carla-simulator/carla#4446]
Hello,

I observed that the RGB sensor output is not deterministic over runs. For example over two runs I get the following images:

![000004_002](https://user-images.githubusercontent.com/27847735/127132209-f74bf5af-1108-4ffe-9156-13222952229d.png)

![000004_0021](https://user-images.githubusercontent.com/27847735/127132219-35c18ec1-8ea0-4e96-a809-ee723f408aca.png)

Although they look similar , the average absolute difference loaded using cv2 is 93.2. 

Question:

I tried disabling post process effects but still I see some delta difference. How do I **control all the rendering attributes** such that I make sure I get consistent images over multiple runs? 

Thanks for your time.

**Comment by DSantosO** [comment]
Hello @pavanteja295,
[Here](https://carla.readthedocs.io/en/0.9.12/bp_library/) you have all the parameters that can be tuned for the camera. Also, it would be good that the simulation is synchronous since the [loading of the map.](https://carla.readthedocs.io/en/0.9.12/adv_synchrony_timestep/#physics-determinism). 
But even with all of that, we cannot assure full determinism for the camera output. because there are some aspects of the rendering of Unreal that break it.
