### ISSUE TITLE
How to perform emergency stop when collision happens?

### ISSUE THREAD

**Issue by EchoYJJ** [carla-simulator/carla#4561]
Hi everyone! When running _automatic_control.py_ in CARLA 0.9.10, I notice that the vehicle will keeping moving after collision which is far from the reality. I'm wondering how vehicle can perform **emergency stop** after collision and then keep static.

To achieve this, I've made a few tries, but it doesn't work.

①CollisionSensor: **automatic_control.py** defines **_on_collision()** to illustrate the reaction on collision , but it's just statistical for HUD. Consequently, I add the reaction control through **apply_control**. However, it fails probably because the emergence stop command only work when collision happens. So the vehicles must keep colliding to maintain braking which is unrealistic.
Code:
    def _on_collision(weak_self, event):
        """On collision method"""
        self = weak_self()
        if not self:
            return
        **self._parent.apply_control(carla.VehicleControl(steer=0.0, throttle=0.0, brake=1.0, hand_brake=False))**
        actor_type = get_actor_display_name(event.other_actor)
        self.hud.notification('Collision with %r' % actor_type)
        impulse = event.normal_impulse
        intensity = math.sqrt(impulse.x ** 2 + impulse.y ** 2 + impulse.z ** 2)
        self.history.append((event.frame, intensity))
        if len(self.history) > 4000:
            self.history.pop(0)

②Agent: The mechanism of vehicle in automatic_control.py is agent. However, it's hard for agent to obtain collision information.(which is easy for actor)

If you have any insight, please give me some advices, thanks in advance!

**Comment by glopezdiest** [comment]
Hey @EchoYJJ. According to your comment, "I'm wondering how vehicle can perform emergency stop after collision and then keep static.". This is exactly what you are doing with the collision sensor, you detect a collision, stop, and then when the collision is over, start again. If you want it to remain static my question is, until when? You'd have to add some kind of condition / timer once a collision is detected that will keep the vehicle static.

Regarding agents, what they try to do is predict whether or not a close-by actor is in their route, braking before they collide with it, but this is done using only waypoint lanes and roads, which fail miserably at junctions. We updated the agents for 0.9.12 but that is still an issue we have to resolve. In order to detect collisions, you can just copy the code that implements a collision sensor at *automatic_control.py*, and when a collision occurs, change a class varaible that you are monitoring on runtime.

Did any of this help? Not sure exactly what you are trying to do so I might be talking about something completely unrelated

**Comment by EchoYJJ** [comment]
Hi @glopezdiest ,thanks a lot for your reply. It really helps!
