### ISSUE TITLE
Where is /Game/Maps/Town02 located, Windows version?

### ISSUE THREAD

**Issue by m090009** [carla-simulator/carla#461]
I just beginning to use the simulator, and did some work with the default `Town01`, my question is where is `Town02` located I can't find it anywhere, I must be missing something.

**Comment by m090009** [comment]
So how can I run the simulator with **Town02**, I did this  `CarlaUE4.exe /Game/Maps/Town02` but neither `maps` nor `Game` folders are in the Windows installation

**Comment by juaxix** [comment]
It refers to the Unreal project content folder, so, it's inside the .pak file of the build version (each platform has different pak files, example: \CarlaUE4\Content\Paks\CarlaUE4-WindowsNoEditor.pak ) but if you open the editor it would be something like CARLA/Unreal/CarlaUE4/Content/Maps/Town02.umap

**Comment by m090009** [comment]
Ok, So is there a way form me to run the Windows build version with Town02?

**Comment by m090009** [comment]
Thanks a lot @juaxix , its working now. Yeah levelSetting would be great for pre-programmed sim.

**Comment by chengjinjack** [comment]
Hello,@juaxix 
Is there any way to add my own map into  the .pak file of the build version? so I could run carla by `./CarlaUE4.sh /Game/Maps/mymap ` and could load my own map.

**Comment by Derekabc** [comment]
@JackRen88 have you solved your problem. I now create a map and then I use the "make package" to create a package, but I cannot find my map in the Maps folder.

**Comment by tsc1989** [comment]
this works for me
CarlaUE4.exe Town01  --carla-server

**Comment by nimishamanjali** [comment]
> Hello,@juaxix
> Is there any way to add my own map into the .pak file of the build version? so I could run carla by `./CarlaUE4.sh /Game/Maps/mymap ` and could load my own map.

Have you found a solution?

**Comment by ivevasiljevic** [comment]
> Hello,@juaxix Is there any way to add my own map into the .pak file of the build version? so I could run carla by `./CarlaUE4.sh /Game/Maps/mymap ` and could load my own map.

Any solution on this?

**Comment by ivevasiljevic** [comment]
So I managed to do it and I hope this will help someone in the future.

RoadRunner:

Create your map and export it using Carla Filmbox, you get .xodr and .fbx files inside of a Exports folder inside of your RoadRunner project

Carla (Source build):

1. Take .fbx and .xodr file and place them into the Import folder
2. Using x64 VS 2019 cmd window while being at the root of your Carla folder, run make import ARGS="--package=exp_town"
3. You will get your package created inside of [Carla root]\Unreal\CarlaUE4\Content\exp_town (default is map_package)
4. Once that is done, you will be able to open this map inside of your Unreal Carla Editor where you can do further customization, like adding a spawn point, etc ...
5. Once you're done editing, using the x64 VS 2019 cmd from the root Carla folder, run make package ARGS="--packages=exp_town"
6. When that finishes you will get one zip file and one folder with the same names inside of [Carla root]\Build\UE4Carla
7. Now simply take that zip file and distribute it whereever you want and use the python config.py --map "map_name" command to change the map in your NoEditor Carla Server. What I do is since I have a VM where I keep my source built Carla I take that folder and transfer the contents of it to my binary built Carla on my local computer.

**Comment by CMakey** [comment]
> It refers to the Unreal project content folder, so, it's inside the .pak file of the build version (each platform has different pak files, example: \CarlaUE4\Content\Paks\CarlaUE4-WindowsNoEditor.pak ) but if you open the editor it would be something like CARLA/Unreal/CarlaUE4/Content/Maps/Town02.umap

hello, i'm meeting the problem that after downloading the 0.8.4 version and run `sh ./CarlaUE4.sh /Game/Carla/Maps/Town01 -windowed -world-port=2000  -benchmark -fps=10` it came error that 
`the map specified on the commandline '/Game/Carla/Maps/Town01' couldn't be found. Would you like to load the default map instead? `. 

And I want to edit the .pak file but I can't open it , could u give me some suggestion how to solve it.
