### ISSUE TITLE
Distorted and Transparent Objects

### ISSUE THREAD

**Issue by mrcoee** [carla-simulator/carla#4761]
I currently would like to generate a few thousand images of random traffic scenes. For this purpose I randomly spawn pedestrians and vehicles, make an rgb and an sematic segmantation image, and despwan every spawned objects afterwards. Unfortunately I occasionally get partially/fully distored vehicles and transparent pedestrians:

![1_9](https://user-images.githubusercontent.com/80214874/137711459-8a8cf79d-04e0-457d-9ab9-b08f5d4decbb.png)

The RGB sensor attributes are:
image_size_x :1920
image_size_x: 1080
fov: 110 
sensor_tick: 1

I'm using Carla 0.9.11 and 0.9.12 on Ubuntu18.04.

**Comment by MattRowe18** [comment]
@mrcoee it may be that the camera catches the vehicles or the pedestrians as they are being spawned or destroyed. Some operations CARLA are multithreaded and asynchronous, including the operations that render sensor images, therefore one thread may be spawning the vehicle while another thread samples the sensor image.

Are you using CARLA in synchronous mode? If not, this could help solve the problem. If you are already using synchronous mode, I would then suggest dividing your process into spawn cycles and image cycles. i.e. spawn hundreds of vehicles and pedestrians, tick() numerous times, then randomly place your cameras and take the images, then rinse and repeat.

If the problem persists, please reopen this issue.

**Comment by yuvalHG** [comment]
@MattRowe18 I work with synchronous mode (Carla 9.11), first spawning all actors and later after applying auto pilot to each, snap images from RGB camera on the Ego vehicle and same problem is observed.

It seems that this issue of fuzzy images / not fully rendered vehicles is repeatedly reported, here are some examples:
1. [[https://github.com/carla-simulator/carla/issues/4860](url)](https://github.com/carla-simulator/carla/issues/4860#issue-1048639255)
2. https://github.com/carla-simulator/carla/issues/4764#issue-1029917913

Is there any walkaround for this issue?
Is it due to improper chose of camera parameters?

Thanks
Yuval

**Comment by wuhanstudio** [comment]
Similar issue using Carla 0.9.14:
![0020](https://github.com/carla-simulator/carla/assets/15157070/f7408910-0cdd-4cf1-82e6-db534b49de06)
