### ISSUE TITLE
Detect Zebra crossings in CARLA

### ISSUE THREAD

**Issue by bhuvanharlapur** [carla-simulator/carla#4801]
Hello,
I am working on detecting crosswalks in CARLA data. I want to create ground truths with bounding 2D box data of crosswalks. How can i get the crosswalks road marking objects?

**Comment by bhuvanofc** [comment]
@XGodina Continuing on my previous comment. Is There a way to give separate labels to Zebra crossings in City Palette. So that i can easily draw bounding boxes on the Zebra crossings. If it is not possible, Is there a way to mark bounding boxes on Zebra crossings from Carla itself

**Comment by XGodina** [comment]
Hello @bhuvanharlapur 
Currently, the crosswalk is included in the Land Markings label because they are the same geometry.
A good way to do that will be to cut the geometry (crosswalk part) and create a new tag for semantic segmentation.
Here you have documentation on how to do that.
https://carla.readthedocs.io/en/0.9.13/tuto_D_create_semantic_tags/#create-semantic-tags
