### ISSUE TITLE
External equippment requires Python > 3.8 causes conflict with CARLA's (0.9.8) dependence on Python 3.7

### ISSUE THREAD

**Issue by ghost** [carla-simulator/carla#5162]
CARLA version == 0.9.8
Python version == 3.8.5
Opration systems == Windows

Hi, I have been trying to use the eyetracker API during driving in CARLA, but I ran into error which of python version conflict ().
CARLA 0.9.8 works fine with Python3.7, but it don't work with Python3.8.

I guess this problem can be solved by using the corresponding egg file (carla-0.9.8-py3.8-win-amd64.egg, not the default py3.7 egg file), but where can I find guidence on generating it using CARLA from source? Thanks very much for all helps! Many thanks!

**Comment by MunchZkin** [comment]
Hi!,
I had a similar issue, and the actual way of getting this to work is building carla from source and while building your PythonAPI you can pass the following args `make PythonAPI ARGS="--python-version=3.8"` to generate an .egg file with py3.8.

Since this does not always work for me I just do `python3.8 -m pip install carla==0.9.12` and it should work

**Comment by yhhSTM05** [comment]
> Hi!, I had a similar issue, and the actual way of getting this to work is building carla from source and while building your PythonAPI you can pass the following args `make PythonAPI ARGS="--python-version=3.8"` to generate an .egg file with py3.8.
> 
> Since this does not always work for me I just do `python3.8 -m pip install carla==0.9.12` and it should work

Many thanks for your help!! I will try this method later!
