### ISSUE TITLE
Using Carla as visualizer for trajectory file (csv data)

### ISSUE THREAD

**Issue by brunnerpascal** [carla-simulator/carla#5190]
Hi together,

Within the consortium of our research project we have trajectory files (x,y position, heading and vehicleID every 100ms) and would love to visualize them (for the map we have a FBX and OpenDRIVE file). I suggested in our team to try CARLA.

I think using CARLA as demonstrator could be a use case somebody already did...
As my research is focusing on math, statistics and modelling I would be happy to save time with the visualizing part 
if there is already some solution available.

Does anybody know if there is already any functionality for that or a Github repository for that purpose? 

I would be pleased about input.

Thank you!

**Comment by pjk19942** [comment]
Hi, was wondering if you found a way?

**Comment by jiaqi-lian** [comment]
hi, I wonder if you've found a way

**Comment by pjk19942** [comment]
Hi, yeah kind of. I have a csv file with X,Y Z and Yaw Pitch and roll data along with timestamp . All i had to do was to extract the the data from the csv and then pass it as a location at every time stamp to my vehicle such as below. 

# Extracting CSV data into a variable , which includes timestamp, XYZ coordinates, and Yaw, Pitch, and Roll angles.
for timestamp, xyz, ypr in my_trajectory:
    # Creating a rotation object based on the extracted Yaw, Pitch, and Roll angles.
    rotation = carla.Rotation(yaw_csv, pitch_csv, roll_csv)  # Replace with the desired rotation values

    # Spawning a vehicle actor in the world using the chosen vehicle blueprint and setting its transformation.
    vehicle = world.spawn_actor(vehicle_blueprints[0], carla.Transform(location))
    vehicle.set_transform(carla.Transform(carla.Location(x=x_csv, y=y_csv, z=z_csv), rotation))
    time.sleep(sampletime)

**Comment by jiaqi-lian** [comment]
Maybe you misunderstood me, I would rather like to know if there is a way to generate an opendrive format map from a csv file

**Comment by liuyueChang** [comment]
Hi, was wondering if you found a way?

**Comment by vollkornholztuer** [comment]
I also have a similar use case for carla. Have you found a solution?

**Comment by minhaj6** [comment]
Have any of you found any solution 🤒

**Comment by Charles8971** [comment]
I'm currently working on this stuff. 
I have applied cubic spline interpolation to generate smooth trajectories for vehicles and pedestrians. However, when I tried multiple position updates to move them along these trajectories, the wheels stayed still and pedestrians appeared to glide across the streets, rather than moving realistically.
Anyone heeeelps me?

**Comment by Charles8971** [comment]
Hi there,

Although quite some time has passed, I eventually managed to build what I was looking for:

https://github.com/tsinghua-fib-lab/Wayla

Regarding the issue I mentioned before (vehicles moving with static wheels and pedestrians sliding), I spent quite a bit of time investigating it and even discussed it with CARLA developers. It turns out that some animations are simply unavailable when actors are driven through this kind of non-physical simulation, so it wasn't caused by the trajectory interpolation itself.

The project currently uses Waymo datasets as its standard input format, but it should be possible to replay custom trajectory CSV files by adapting the OpenDRIVE (XODR) map interface and the CSV playback interface.

The visuals are not particularly polished since I didn't use RoadRunner for scene editing. My goal was mainly to create a practical trajectory visualization tool rather than a photorealistic demonstration.

Hopefully it can be useful to you or anyone else facing a similar problem.
