### ISSUE TITLE
How to create a level with map elements like Town[1-10] only from an openDrive map?

### ISSUE THREAD

**Issue by Utopialjp** [carla-simulator/carla#5411]
CARLA version: 0.9.13
Platform/OS: Linux/Ubuntu

I have an openDrive map, but no RoadRunner. Referring to document [OpenDRIVE standalone mode](https://carla.readthedocs.io/en/latest/adv_opendrive/), now I can open level OpenDriveMap.umap. When I play in UE Editor, the  actor OpenDriveGenerator will spawn some actors about map elements like this.
![image](https://user-images.githubusercontent.com/23400855/167065891-a5fa855b-7cd2-466c-a87f-607d95a4e7d4.png)

But when play ends, these actors are gone. How can I save these actors into a Level like Town[1-10], so that I can see them directly when I open the level without OpenDriveGenerator?

**Comment by Blyron** [comment]
You can select the components of each mesh and then select generate staticmesh so the meshes will be generated and you can place those in a map creating a new map. Otherwise you can put the Path to your XODR in UW_OnRoadMainWidget and it will generate the map. take care with this as the origin of the map must be in top left corner of it
