### ISSUE TITLE
Zlib version outdated

### ISSUE THREAD

**Issue by wuxiaohua1011** [carla-simulator/carla#5570]
CARLA version: 0.9.12
Platform/OS: Windows 11
Problem you have experienced:
Zlib version 1.2.11 does not exist anymore and therefore installation script fails for windows

What you expected to happen:
Installation script to be successful

Steps to reproduce:
Other information (documentation you consulted, workarounds you tried):
1. `git clone https://github.com/carla-simulator/carla`
2. git checkout 0.9.12
3. move the assets downloaded from indicated [file](https://github.com/carla-simulator/carla/blob/master/Util/ContentVersions.txt) to the `../carla/Unreal/CarlaUE4/Content/Carla` folder
4. `make launch`

Here is the trace log

![Screen Shot 2022-07-07 at 12 13 59](https://user-images.githubusercontent.com/17909837/177853686-ed096a38-0188-4655-b07e-ab68d89bbc1d.png)

This is the line that indicated the url in the build bat

https://github.com/carla-simulator/carla/blob/0.9.12/Util/InstallersWin/install_zlib.bat#L57

**Comment by 00Markus0** [comment]
Hi, the temporary fix for this issue is to go into the file
"%carlaFolder%/Util/InstallersWin" and right click on "install_zlib.bat" and select "edit"
In this file you go to line 50 or search for "ZLIB_VERSION" and change the value from 1.2.11 to 1.2.12

This problem is adresses in #5337, but the Pull request is still in review
