### ISSUE TITLE
Unreal engine not detected 'make launch'

### ISSUE THREAD

**Issue by arsalan0302** [carla-simulator/carla#5765]

**Comment by arsalan0302** [comment]
I am facing the following error when I run 'make launch' command, I followed  windows build carla Docs step by step but still same error happens.
please share your ideas.
Thank You!
![launch error](https://user-images.githubusercontent.com/112169068/190849794-75d85530-1084-4fcb-8d43-d200b6d4a56a.PNG)

**Comment by Blyron** [comment]
You have to set Enviorment variable of your Unreal Engine Path
You haven't set properly the ENV Variable
Set Unreal Engine environment variable
It is necessary to set an environment variable so that CARLA can find the Unreal Engine installation folder. This allows users to choose which specific version of Unreal Engine is to be used. If no environment variable is specified, then CARLA will search for Unreal Engine in the windows registry and use the first version it finds there.

To set the environment variable:

Open Windows Control Panel and go to Advanced System Settings or search for Advanced System Settings in the Windows search bar.
On the Advanced panel open Environment Variables....
Click New... to create the variable.
Name the variable UE4_ROOT and choose the path to the installation folder of the desired Unreal Engine installation.
