### ISSUE TITLE
understand lidar ray-cast 

### ISSUE THREAD

**Issue by mhusseinsh** [carla-simulator/carla#581]
Hello,
I am kind of new a little bit to lidar data and usage
I understand the data of the lidar from points, channels, FOV and everything
But I want to understand what is the ray-cast ?

**Comment by luigui2906** [comment]
Hi @mhusseinsh,

I think the ray-cast operation consists in following the ray from the origin (the sensor) to the intersection with a surface which in this case would represent the coordinates of the impacted point. I guess this is what is done in order to obtain the point cloud data in the simulator.

Hope this helps.

**Comment by mhusseinsh** [comment]
Thanks a lot :)

**Comment by hamza422** [comment]
@@mhusseinsh @marcgpuig  I want to ask a question-related ray cast. As they explain in Unreal's article to highlight the object where the ray hits. I want to make it work in Carla. Can Lidar sensor do raycasting in a pointing direction? like a ray?
Would you help me with this?
