### ISSUE TITLE
"/usr/bin/sh: rd: command not found" on WINDOWS 7 x64

### ISSUE THREAD

**Issue by NYJiaxing** [carla-simulator/carla#608]
I installed the Make and CMake in my computer and Enable a 64-Bit Visual C++ Toolset on the Command Line as well. . I follow the steps in the documents on CARLA: https://carla.readthedocs.io/en/latest/how_to_build_on_windows/.  So far so good!

Now, I have an issue when run the Rebuild.bat. There is an issue prompt out said "/usr/bin/sh: rd: command not found" just like you mention in the Note that:

"Take care if you have Cygwin installed. This could cause the errors like
/usr/bin/sh: rd: command not found While executing Reuild.bat. "

However, I didn't install the Cygwin, so any solution on this? I saw some closed issue about this issue but it only related with Linux, so can you help me solve this issue in Windows OS?

Thank you so much!

**Comment by marcgpuig** [comment]
Hi @NYJiaxing.

This is a common problem, this error means that you have a bash interpreter in your path.

When you run Rebuild.bat, it calls `rd` that is the [Delete folder(s)](https://ss64.com/nt/rd.html) command for Windows.
However! If you have in your path some bash interpreter, sometimes, somehow, it will try to run the your commands as Linux commands. This is probably because a wrong order of paths in the PATH windows variable. Also check out your user's PATH too ;)

As far as I've seen this may occur when you have installed **SourceTree** or **Cygwin**. I'll will update this list if I see more softwares!

**Comment by marcgpuig** [comment]
Oops! Miss-click closing the issue.

**Comment by NYJiaxing** [comment]
Hi @marcgpuig,

Thank you for your reply, I just reinstall the python and delete all the Cygwin related files I can find in my computer. However, it still report the same issue.

**Comment by marcgpuig** [comment]
Check if `C:\Program Files\Git\bin` is in your path. I'm not sure if having it may cause problems.
