### ISSUE TITLE
how to load other maps and obtain 2d map data?

### ISSUE THREAD

**Issue by WillenPeng** [carla-simulator/carla#676]
Hi,

I run carla 0.8.2 with ubuntu. I want to ask how to load other maps such as Town02.umap and testmaptruck.umap in Unreal Engine. I had take a look at the tutorials, but not found /Game/carla/Maps. I also run the maps I found in Unreal Engine folder, but it still not work.

Another question how to obtain the corresponding 2d map? can i use ros to publish this info as a topic. Because I want to use this info to implement other algorithms.

Thanks

**Comment by hxlee309** [comment]
We saved all the maps in the folder called "/Games/Maps/". Currently we have two big problems:

1. The only maps we can load are Town01.umap and Town02.umap
2. After significantly modifying the map Town01.umap using editor, and run the simulator using the command "./CarlaUE4.sh /Game/Maps/Town01.umap", what we can see is still the old Town01 map instead of the modified one.

Any help will be appreciated.

Hanxiang

**Comment by danil-tolkachev** [comment]
Hi @WillenPeng 

For the second question look at the #537 (it's not merged yet). I used `CarlaMap` class to generate ROS OccupancyGrid message.

**Comment by lihanxiang0309** [comment]
Hi @danil-tolkachev 

Thanks it works! Now we succeed in generating the 2d occupancy map (2600 x 2200). However, we are confused about how to convert the world x-y coordinate into the 2d map pixel index?

Thanks

**Comment by danil-tolkachev** [comment]
There is a `convert_to_pixel` method in the `CarlaMap` class. You can also look at the `view_start_positions.py` example.

**Comment by chengjinjack** [comment]
@hxlee309 
hello!
Excuse me, have you solved the second question?
