### ISSUE TITLE
How to get longitudinal and lateral velocities?

### ISSUE THREAD

**Issue by Anhar2** [carla-simulator/carla#7308]
I'm using CARLA 0.9.14 "with leaderboard v2" on Ubuntu 20 Focal Fossa

In a scenario, I use get_velocity() to return the x and y velocities, how to transform these values into longitudinal and lateral velocities as I need them to calculate RSS measurements such as MSDV?

**Comment by glopezdiest** [comment]
@Anhar2 You can't really do that unfortunately. The only solution is to create a new function that instead of returning the speed, it returns the velocity vector. That means:

1) Adding a 4th map similar to the `CarlaDataProvider._actor_velocity_map`, `CarlaDataProvider._actor_location_map` and `CarlaDataProvider._actor_transform_map` ones
2) Update it on the `on_carla_tick()`
3) Create the getter

**Comment by Anhar2** [comment]
> @Anhar2 You can't really do that unfortunately. The only solution is to create a new function that instead of returning the speed, it returns the velocity vector. That means:
> 
> 1. Adding a 4th map similar to the `CarlaDataProvider._actor_velocity_map`, `CarlaDataProvider._actor_location_map` and `CarlaDataProvider._actor_transform_map` ones
> 2. Update it on the `on_carla_tick()`
> 3. Create the getter

Thank you for Your response!
