### ISSUE TITLE
SM on UE5.3

### ISSUE THREAD

**Issue by rldiaz14** [carla-simulator/carla#7926]
CARLA version: UE5.3 Dev
Platform/OS: Window
Problem you have experienced: missing mesh
What you expected to happen: load the map with the mesh. 
I follow this step,
git clone -b ue5-dev https://github.com/carla-simulator/carla.git CarlaUE5
Run the setup script:

cd CarlaUE5
Setup.bat
Configure. Open x64 Native Tools Command Prompt for VS 2022 at the CarlaUE5 folder and runn the following command:
cmake -G Ninja -S . -B Build -DCMAKE_BUILD_TYPE=Release -DBUILD_CARLA_UNREAL=ON -DCARLA_UNREAL_ENGINE_PATH=%CARLA_UNREAL_ENGINE_PATH%
Build CARLA. Open the x64 Native Tools Command Prompt for VS 2022 at the CarlaUE5 folder and run the following command:
cmake --build Build
Build and install the Python API. Open the x64 Native Tools Command Prompt for VS 2022 at the CarlaUE5 folder and run the following command::
cmake --build Build --target carla-python-api-install
Launch the editor. Open the x64 Native Tools Command Prompt for VS 2022 at the CarlaUE5 folder and run the following command:
cmake --build Build --target launch
but after here I deleted the version that file have download the 
![Screenshot 2024-07-08 13-26-03](https://github.com/carla-simulator/carla/assets/31676069/a0642d33-7a38-4a76-933c-7d25b5f81734)
Then restart the setup.bat again and after the project is build, I have this issue appear
if there a other step to find the meshes or need to rebuild the project again, or cmd command that need to be use. 
![Screenshot 2024-07-08 13-12-28](https://github.com/carla-simulator/carla/assets/31676069/049bc2ed-fe38-4785-a4bf-acf64bf54242)
![Screenshot 2024-07-08 13-12-42](https://github.com/carla-simulator/carla/assets/31676069/c950399e-3915-47fb-9b30-697223d3974d)
Any support that you can provide, it would appreciate.

**Comment by Jinviz** [comment]
First, run Setup.bat and you don't need to run the cmake command line separately because the batch file contains all the cmake commands. 

The problem with CARLA Mesh missing is that the content file is most likely not decompressed. Downloading the content file is also included in Setup.bat, which starts downloading and decompressing asynchronously when you run Setup.bat. Please check it out in these file. 

make sure that there are uncompressed files on the path "C:\Users\USER\CarlaUE5\Unreal\CarlaUnreal\Content" and if no problem is found, you will need to download the content file yourself. Find the content file that supports CARLA 0.10.0 and download it yourself. I hope you get good results.
