### ISSUE TITLE
TCP Frame communication description, Client<->Server

### ISSUE THREAD

**Issue by Jabkowsky** [carla-simulator/carla#859]
Hello 

I need to ask for documentation/information about TCP client-server frame content. 
Some description of host communication content/frame/header and other. Generally how the frame is  build.
Our goal is to create our own client to communicate with Carla server. ( not in python) 
I do want to avoid wasting time with reverse engineering the tcp frame content.
I would really appreciate if any documentation or information can be provided.

**Comment by nsubiron** [comment]
Hi @Jabkowsky,

I'm guessing you are using our stable version? If that's the case, the TCP protocol is [documented here](https://carla.readthedocs.io/en/stable/carla_server/). Also there has been already some effort porting the PythonClient to C++ (#690).

With newer versions (starting at 0.9.0), the protocol has changed drastically. In order to support multiple clients connecting and controlling every actor in the scene, we have switched to a "dual" server (RPC + streaming).

![image](https://user-images.githubusercontent.com/4332953/46796756-b6ed9700-cd4d-11e8-8415-916fade59146.png)

The RPC channel gives a bidirectional communication between server and client, very flexible for us to add new functionality and quite robust to disconnections. The streaming channel is used for sending the data generated by the sensors, much faster than the RPC protocol, but only works in one direction. We use [rpclib](http://rpclib.net/) for the RPC channel and our own implementation for the streaming server that basically sends the raw memory as generated by the sensor. At this point we are still developing this protocol we cannot guarantee that some details may change. In case you want to use this version, I would really recommend using the API we provide. We have a quite stable Python API, but we are also developing a C++ API. In case you are willing to put some effort into a C++ API, it would be really appreciated if instead you can contribute to our own so the whole community can benefit from it :)  (C++ or otherwise encapsulating it in a C header to be imported in any other language).
